"use client";

import { useMemo, useState } from "react";
import { concepts, events, items, navigation, recommendations, type Locale, type View } from "./adaptiveData";

const copy = { en: { tenant: "Maple Leaf Learning", env: "Production", search: "Search learners, concepts, items…", title: "Good morning, Alex.", subtitle: "Your adaptive engine is healthy and learning across Ontario Mathematics.", updated: "Updated just now" }, fr: { tenant: "Apprentissage Feuille d’érable", env: "Production", search: "Rechercher apprenants, concepts…", title: "Bonjour, Alex.", subtitle: "Votre moteur adaptatif fonctionne bien dans le curriculum de mathématiques de l’Ontario.", updated: "Mis à jour à l’instant" } };
const tone = (value: number) => value >= 75 ? "green" : value >= 55 ? "amber" : "red";

export function AdaptiveHub() {
  const [view, setView] = useState<View>(() => { if (typeof window === "undefined") return "overview"; const hash = location.hash.slice(1) as View; return navigation.some(g => g.items.some(i => i.id === hash)) ? hash : "overview"; });
  const [locale, setLocale] = useState<Locale>("en");
  const [menu, setMenu] = useState(false);
  const [query, setQuery] = useState("");
  const [toast, setToast] = useState("");
  const go = (id: View) => { setView(id); setMenu(false); history.replaceState(null, "", `#${id}`); scrollTo({ top: 0, behavior: "smooth" }); };
  const flash = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2600); };
  const matches = useMemo(() => query ? [...concepts.map(c => ({ id: "curriculum" as View, title: `${c.code} · ${locale === "fr" ? c.fr : c.title}` })), ...items.map(i => ({ id: "content" as View, title: `${i.id} · ${i.title}` }))].filter(x => x.title.toLowerCase().includes(query.toLowerCase())).slice(0, 6) : [], [query, locale]);
  const c = copy[locale];
  return <div className="ae-shell">
    <button className={`ae-scrim ${menu ? "show" : ""}`} onClick={() => setMenu(false)} aria-label="Close navigation" />
    <aside className={`ae-side ${menu ? "open" : ""}`}>
      <div className="ae-brand"><div className="ae-logo">O</div><div><strong>Opyjo</strong><span>Adaptive Engine</span></div></div>
      <button className="ae-tenant"><span className="tenant-avatar">ML</span><span><strong>{c.tenant}</strong><small>{c.env} · Canada Central</small></span><b>⌄</b></button>
      <nav>{navigation.map(group => <section key={group.label}><p>{group.label}</p>{group.items.map(item => <button key={item.id} onClick={() => go(item.id)} className={view === item.id ? "active" : ""}><i>{item.icon}</i>{locale === "fr" ? item.fr : item.label}{item.id === "sessions" && <em>12</em>}</button>)}</section>)}</nav>
      <div className="ae-side-foot"><span><i /> All systems operational</span><small>Data region · Montréal, Canada</small></div>
    </aside>
    <main className="ae-main">
      <header className="ae-top"><button className="ae-menu" onClick={() => setMenu(true)}>☰</button><div className="ae-search">⌕<input value={query} onChange={e => setQuery(e.target.value)} placeholder={c.search} />{matches.length > 0 && <div>{matches.map(x => <button key={x.title} onClick={() => { go(x.id); setQuery(""); }}>{x.title}<span>→</span></button>)}</div>}</div><div className="ae-top-actions"><button className="locale" onClick={() => setLocale(locale === "en" ? "fr" : "en")}>{locale === "en" ? "FR" : "EN"}</button><button className="help">?</button><button className="bell">♢<i /></button><button className="avatar">AR</button></div></header>
      <div className="ae-content">
        {view === "overview" && <Overview locale={locale} copy={c} go={go} />}
        {view === "curriculum" && <Curriculum locale={locale} flash={flash} />}
        {view === "content" && <Content flash={flash} />}
        {view === "sessions" && <Sessions flash={flash} />}
        {view === "learners" && <Learners locale={locale} />}
        {view === "analytics" && <Analytics />}
        {view === "models" && <Models flash={flash} />}
        {view === "trust" && <Trust flash={flash} />}
        {view === "api" && <Api flash={flash} />}
      </div>
    </main>{toast && <div className="ae-toast">✓ {toast}</div>}
  </div>;
}

function Header({ eyebrow, title, body, action }: { eyebrow: string; title: string; body: string; action?: React.ReactNode }) { return <header className="ae-page-head"><div><span>{eyebrow}</span><h1>{title}</h1><p>{body}</p></div>{action}</header>; }
function Stat({ label, value, delta, kind = "plain" }: { label: string; value: string; delta: string; kind?: string }) { return <article className="ae-stat"><div><span>{label}</span><i className={kind}>{delta}</i></div><strong>{value}</strong><div className="spark">{[24,38,30,52,45,62,58,71,66,84].map((h,i) => <b key={i} style={{height:`${h}%`}} />)}</div></article>; }
function Overview({ locale, copy, go }: { locale: Locale; copy: { title: string; subtitle: string; updated: string }; go: (v: View) => void }) { return <>
  <Header eyebrow="Ontario · Mathematics · Grades 1–8" title={copy.title} body={copy.subtitle} action={<div className="live-pill"><i /> Live engine<span>{copy.updated}</span></div>} />
  <section className="ae-stats"><Stat label="Active learners" value="8,426" delta="↑ 12.4%" kind="up" /><Stat label="Recommendations today" value="24,891" delta="↑ 8.1%" kind="up" /><Stat label="Avg. concept mastery" value="68.4%" delta="↑ 2.7 pts" kind="up" /><Stat label="Median API latency" value="84 ms" delta="↓ 11 ms" kind="up" /></section>
  <section className="ae-grid two"><article className="ae-card"><header><div><span>Learning activity</span><h2>Concept mastery</h2></div><button onClick={() => go("learners")}>View profiles →</button></header><div className="mastery-bars">{concepts.slice(0,5).map(x => <div key={x.code}><span><b>{x.code}</b>{locale === "fr" ? x.fr : x.title}</span><div><i className={tone(x.mastery)} style={{width:`${x.mastery}%`}} /></div><strong>{x.mastery}%</strong></div>)}</div></article>
  <article className="ae-card"><header><div><span>Decision stream</span><h2>Recent recommendations</h2></div><button onClick={() => go("sessions")}>View all →</button></header><div className="rec-list">{recommendations.map(r => <div key={r.learner}><i className={r.action.toLowerCase()}>{r.action[0]}</i><span><strong>{r.action} {r.concept}</strong><small>{r.learner} · {r.reason.replaceAll("_", " ").toLowerCase()}</small></span><em>{r.confidence}%</em></div>)}</div></article></section>
  <section className="ae-grid bottom"><article className="ae-card activity"><header><div><span>Evidence</span><h2>Live learning events</h2></div><span className="streaming"><i /> Streaming</span></header>{events.map(e => <div className="event" key={`${e.learner}${e.time}`}><code>{e.learner}</code><span><strong>{e.concept}</strong><small>{e.meta}</small></span><b className={e.outcome === "Correct" ? "correct" : "incorrect"}>{e.outcome}</b><time>{e.time}</time></div>)}</article><article className="ae-card coverage"><header><div><span>Curriculum</span><h2>Ontario coverage</h2></div></header><div className="coverage-ring"><div><strong>78%</strong><span>mapped</span></div></div><p><b>312</b> of 401 expectations have active content</p><button onClick={() => go("curriculum")}>Explore curriculum graph</button></article></section>
  <div className="model-strip"><span className="model-icon">◫</span><div><strong>Adaptive model v2.3 is active</strong><p>Bayesian concept mastery · prerequisite-aware · retention scheduling</p></div><span>Validated Jul 8, 2026</span><button onClick={() => go("models")}>Model card →</button></div>
  </>; }

function Curriculum({ locale, flash }: { locale: Locale; flash: (s:string)=>void }) { const [strand,setStrand]=useState("All"); const shown=concepts.filter(c=>strand==="All"||c.strand===strand); return <><Header eyebrow="Curriculum catalogue" title="A versioned map of what learners know." body="Official Ontario expectations stay separate from publisher extensions, with traceable prerequisites and bilingual metadata." action={<button className="ae-primary" onClick={()=>flash("Curriculum import validation started")}>Import curriculum</button>} /><div className="context-bar"><span>Jurisdiction <b>Ontario</b></span><span>Package <b>Mathematics 2020</b></span><span>Grade <b>2</b></span><span>Version <b>1.4 · Active</b></span></div><div className="filter-row">{["All","Number","Algebra","Data","Spatial Sense","Financial Literacy"].map(s=><button className={strand===s?"active":""} onClick={()=>setStrand(s)} key={s}>{s}</button>)}</div><section className="concept-list">{shown.map((x,i)=><article key={x.code}><div className="concept-code">{x.code}<i>{i<shown.length-1?"↓":""}</i></div><div><span>{x.strand} · Grade {x.grade}</span><h3>{locale==="fr"?x.fr:x.title}</h3><p>{x.prereqs.length?`Prerequisites: ${x.prereqs.join(", ")}`:"No prerequisite in this package"}</p></div><div className="concept-meta"><span><b>{x.items}</b> mapped items</span><span><b>{x.confidence}%</b> evidence confidence</span><button aria-label="Open concept">→</button></div></article>)}</section></>; }
function Content({ flash }: { flash:(s:string)=>void }) { return <><Header eyebrow="Publisher content" title="Content mapped to concepts—not locked to a course." body="Keep answer keys and presentation in your platform. Opyjo stores only the metadata needed to adapt and evaluate." action={<button className="ae-primary" onClick={()=>flash("Item import ready for upload")}>＋ Import items</button>} /><section className="ae-card table-card"><header><div><span>Content health</span><h2>Item calibration</h2></div><div className="mini-stats"><span><b>2,486</b> items</span><span><b>83%</b> calibrated</span><span><b>14</b> review flags</span></div></header><div className="ae-table"><div className="tr th"><span>Item</span><span>Concept mapping</span><span>Prior / empirical</span><span>Discrimination</span><span>Exposure</span><span>Status</span></div>{items.map(x=><div className="tr" key={x.id}><span><code>{x.id}</code><b>{x.title}</b></span><span>{x.concepts.map(c=><em key={c}>{c}</em>)}</span><span>{x.prior} / <b>{x.empirical}</b></span><span>{x.discrimination}</span><span>{x.exposure}</span><span><i className={x.status==="Healthy"?"healthy":"review"}>{x.status}</i></span></div>)}</div></section></>; }
function Sessions({ flash }: { flash:(s:string)=>void }) { const [goal,setGoal]=useState("Diagnostic"); return <><Header eyebrow="Adaptive delivery" title="Every next action has a reason." body="Create goal-aware sessions and let the engine select diagnostic, practice, remediation, or review actions within your constraints." action={<button className="ae-primary" onClick={()=>flash(`${goal} session created: ssn_${Math.random().toString(16).slice(2,8)}`)}>＋ Create session</button>} /><section className="session-builder"><div><span>Session goal</span><div>{["Diagnostic","Practice","Remediation","Review"].map(g=><button className={goal===g?"active":""} key={g} onClick={()=>setGoal(g)}>{g}</button>)}</div></div><div><span>Target</span><strong>Ontario · Grade 2 · Number</strong></div><div><span>Strategy</span><strong>balanced-v2.3</strong></div></section><section className="ae-grid two"><article className="ae-card decision-card"><span>Next recommendation preview</span><div className="decision-path"><div><small>01 · learner state</small><strong>B2.2 mastery 61%</strong><p>Confidence 68% · 7 observations</p></div><b>→</b><div><small>02 · prerequisite check</small><strong>B2.1 is available</strong><p>Mastery 74% · above threshold</p></div><b>→</b><div className="selected"><small>03 · action</small><strong>{goal}</strong><p>itm_1048 · confidence 87%</p></div></div><code>explanation_code: TARGET_CONCEPT_UNCERTAIN</code></article><article className="ae-card overrides"><span>Human controls</span><h2>Educator constraints</h2>{["Allow prerequisite remediation","Respect publisher item exclusions","Cap challenge above current grade","Enable spaced review"].map((x,i)=><label key={x}>{x}<input type="checkbox" defaultChecked={i!==2}/><i /></label>)}</article></section></>; }
function Learners({ locale }: { locale:Locale }) { return <><Header eyebrow="Pseudonymous profiles" title="Mastery with uncertainty—not a permanent label." body="Profiles expose evidence, confidence and retention risk. Tenants retain learner identity and control deletion." /><div className="profile-head"><span className="big-avatar">7F</span><div><code>lrn_7f2a</code><h2>Grade 2 mathematics</h2><p>Last evidence 2 minutes ago · 42 events · no direct identifiers</p></div><button>Export profile</button><button className="danger">Delete</button></div><section className="ae-card table-card"><header><div><span>Concept state</span><h2>Mastery profile</h2></div></header><div className="ae-table learner-table"><div className="tr th"><span>Concept</span><span>Mastery</span><span>Confidence</span><span>Evidence</span><span>Retention risk</span><span>Updated</span></div>{concepts.map(x=><div className="tr" key={x.code}><span><code>{x.code}</code><b>{locale==="fr"?x.fr:x.title}</b></span><span><div className="inline-bar"><i style={{width:`${x.mastery}%`}} /></div><b>{x.mastery}%</b></span><span>{x.confidence}%</span><span>{Math.round(x.confidence/7)} events</span><span><i className={x.mastery<60?"risk":"healthy"}>{x.mastery<60?"Elevated":"Low"}</i></span><span>Today</span></div>)}</div></section></>; }
function Analytics() { return <><Header eyebrow="Publisher intelligence" title="Find coverage gaps and content that needs attention." body="Empirical parameters influence live decisions only after minimum evidence thresholds are met." /><section className="ae-stats"><Stat label="Items analysed" value="2,486" delta="↑ 184" kind="up"/><Stat label="Possible defects" value="14" delta="3 new" /><Stat label="Median discrimination" value="0.96" delta="Healthy" kind="up"/><Stat label="Suppressed cohorts" value="7" delta="n < 10" /></section><section className="ae-grid two"><article className="ae-card chart-card"><header><div><span>Calibration</span><h2>Prior vs. empirical difficulty</h2></div></header><div className="scatter">{items.concat(items).map((x,i)=><i key={i} style={{left:`${16+i*10}%`,bottom:`${18+(Number(x.empirical)*17+i%3*5)}%`}} />)}<b /></div><p>Closer to the diagonal means publisher priors match learner evidence.</p></article><article className="ae-card"><header><div><span>Cohort readiness</span><h2>Grade 2 · Number</h2></div><em className="privacy-badge">Minimum cohort n=10</em></header><div className="mastery-bars">{concepts.slice(0,4).map(x=><div key={x.code}><span><b>{x.code}</b>{x.title}</span><div><i className={tone(x.mastery)} style={{width:`${x.mastery}%`}} /></div><strong>{x.mastery}%</strong></div>)}</div><div className="suppressed">🔒 2 small cohorts suppressed to protect learner privacy</div></article></section></>; }
function Models({ flash }: { flash:(s:string)=>void }) { return <><Header eyebrow="Model governance" title="Compare before you activate." body="Every recommendation records its model version. Offline replay evaluates coverage, repetition, latency and subgroup disparities." action={<button className="ae-primary" onClick={()=>flash("Historical replay queued")}>Run evaluation</button>} /><section className="model-hero"><div><span>ACTIVE</span><h2>adaptive-bayes-v2.3</h2><p>Probabilistic concept mastery · prerequisite-aware selection · time-decayed evidence</p><small>Activated July 8, 2026 by Alex R. · Algorithm card ALG-023</small></div><div><span>VALIDATION</span><strong>Passed</strong><p>12/12 acceptance gates</p></div><div><span>ROLLBACK</span><strong>v2.2</strong><p>One-click recovery ready</p></div></section><section className="ae-card comparison"><header><div><span>Historical replay · 1.8M events</span><h2>Version comparison</h2></div></header>{[["Prediction log loss","0.412","0.386","−6.3%"],["Recommendation coverage","94.1%","97.8%","+3.7 pts"],["Repeated-item rate","8.4%","5.9%","−2.5 pts"],["p95 decision latency","141 ms","128 ms","−13 ms"],["Maximum subgroup gap","4.8 pts","4.2 pts","−0.6 pts"]].map((r,i)=><div key={r[0]}><span>{r[0]}</span><span>{i===0&&<small>v2.2</small>}{r[1]}</span><span>{i===0&&<small>v2.3</small>}{r[2]}</span><b>{r[3]}</b></div>)}</section></>; }
function Trust({ flash }: { flash:(s:string)=>void }) { return <><Header eyebrow="Canadian trust layer" title="Privacy and accountability are product features." body="Controls are designed for Canadian education partners, understandable decisions and explicit limits on secondary use." /><section className="trust-grid">{[["⌂","Canadian data residency","All production learner data is stored and processed in Canada Central."],["◈","Purpose limitation","School learner data is never used for marketing or cross-tenant training without authorization."],["⌛","Retention controls","Tenant-defined retention with export, deletion and immutable audit evidence."],["◎","Explainable decisions","Stable explanation codes, confidence values and model versions on every action."],["◇","Human override","Educators can constrain concepts, items, challenge level and recommendation types."],["文","Bilingual readiness","English and French labels, explanations and curriculum metadata." ]].map(x=><article key={x[1]}><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p><a>View control →</a></article>)}</section><section className="ae-card governance"><header><div><span>Tenant controls</span><h2>Research participation</h2></div><i className="off">Opted out</i></header><p>De-identified aggregate model research is disabled. Changing this setting requires an authorized administrator and creates an audit event.</p><button onClick={()=>flash("Participation setting unchanged; administrator approval required")}>Review participation terms</button></section><section className="policy-links">{["Privacy Impact Assessment template","Algorithmic Impact Assessment template","Algorithm card v2.3","Incident response procedure"].map(x=><button onClick={()=>flash(`${x} opened`)} key={x}>{x}<span>↗</span></button>)}</section></>; }
function Api({ flash }: { flash:(s:string)=>void }) { const code=`POST /v2/recommendations\n{\n  "learner_id": "lrn_7f2a",\n  "session_id": "ssn_8c31",\n  "goal": "remediation",\n  "target_concepts": ["B2.2"]\n}`; return <><Header eyebrow="Developer platform" title="Integrate the engine without rebuilding your product." body="Native JSON endpoints preserve your content, identities, presentation and grading. Existing v1 clients remain supported." action={<button className="ae-primary" onClick={()=>flash("API key creation requires administrator approval")}>＋ Create API key</button>} /><section className="api-hero"><div><span>BASE URL</span><code>https://api.opyjo.ca/v2</code><button onClick={()=>navigator.clipboard?.writeText("https://api.opyjo.ca/v2")}>Copy</button></div><div><span>STATUS</span><strong><i /> Operational</strong></div><div><span>REGION</span><strong>ca-central-1</strong></div></section><section className="ae-grid two"><article className="ae-card endpoints"><header><div><span>Core contract</span><h2>Endpoints</h2></div><em>v1 compatible</em></header>{[["GET","/curricula/{id}/concepts"],["PUT","/items/{id}/concepts"],["POST","/learning-events"],["POST","/recommendations"],["GET","/learners/{id}/mastery"],["GET","/analytics/content-quality"]].map(x=><div key={x[1]}><b className={x[0].toLowerCase()}>{x[0]}</b><code>{x[1]}</code><span>›</span></div>)}</article><article className="ae-card code-card"><header><div><span>Example</span><h2>Request a next action</h2></div><button onClick={()=>navigator.clipboard?.writeText(code)}>Copy</button></header><pre>{code}</pre><div className="response"><span>200 OK · 84 ms</span><code>action: remediate · confidence: 0.87 · model: v2.3</code></div></article></section></>; }
