"use client";

import { useMemo, useState } from "react";

type Audience="All"|"Product owner"|"Engineer"|"Privacy reviewer"|"Curriculum specialist"|"Investor"|"Pilot team";
type Lane={title:string;tone:"client"|"engine"|"shared"|"external"|"risk";nodes:string[]};
type Diagram={id:string;number:string;title:string;category:string;summary:string;audiences:Audience[];lanes:Lane[];steps:string[];takeaway:string};
const diagrams:Diagram[]=[
 {id:"ecosystem",number:"01",title:"Complete ecosystem",category:"Context",summary:"Who participates, which systems they control, and how information crosses organizational boundaries.",audiences:["Product owner","Engineer","Privacy reviewer","Investor"],lanes:[{title:"People",tone:"external",nodes:["Learner","Educator","Client administrator"]},{title:"Client organization",tone:"client",nodes:["Web or mobile app","Client backend","Identity mapping","Content + answer keys","Local grader"]},{title:"Adaptive Engine",tone:"engine",nodes:["HTTPS API","Authentication + scopes","Adaptive core","Curriculum graph","Canadian PostgreSQL"]},{title:"External assurance",tone:"shared",nodes:["Curriculum authorities","Reviewers","Canadian cloud region"]}],steps:["Learner uses the client application","Client backend resolves an opaque learner ID","Server calls the engine with a private key","Engine returns item ID, reason and confidence","Client loads, displays and grades its own content"],takeaway:"The learner never calls the engine directly. Content, grading, identity and UI remain with the client."},
 {id:"practice",number:"02",title:"Adaptive practice loop",category:"Runtime",summary:"The complete next-item and answer-event sequence for one learner attempt.",audiences:["Product owner","Engineer","Curriculum specialist","Pilot team"],lanes:[{title:"Learner experience",tone:"external",nodes:["Start practice","View question","Submit response","Receive feedback"]},{title:"Client systems",tone:"client",nodes:["Resolve pseudonym","Request next item","Load question","Grade locally","Report outcome"]},{title:"Engine runtime",tone:"engine",nodes:["Authenticate","Load evidence","Select item","Record decision","Update mastery"]},{title:"Evidence store",tone:"shared",nodes:["Skill state","Selection event","Answer event","Algorithm version"]}],steps:["Request next item with grade and session goal","Authenticate recommendations:read scope","Select from tenant-scoped candidates","Client resolves and displays item","Client grades response locally","Report outcome with stable idempotency key","Update mastery once and return progress"],takeaway:"Recommendation and grading are separate calls. The client grades; the engine learns from the resulting evidence."},
 {id:"privacy",number:"03",title:"Data and privacy boundary",category:"Trust",summary:"What stays with the client, what the engine accepts, and what is prohibited by product policy.",audiences:["Product owner","Engineer","Privacy reviewer","Investor"],lanes:[{title:"Client only",tone:"client",nodes:["Names + emails","Question content","Answer keys","Raw response","Official grades","Login tokens"]},{title:"Engine minimum",tone:"engine",nodes:["Tenant ID","Opaque learner ID","Item metadata","Correct / incorrect","Optional timing + hints","Mastery + decision"]},{title:"Do not send",tone:"risk",nodes:["Disability details","Emotion inference","Biometrics","Advertising profiles","Unrelated behaviour"]}],steps:["Map account to pseudonym inside client systems","Export item metadata—not content","Grade raw response locally","Send outcome to update model state","Return an explainable recommendation"],takeaway:"Pseudonymous data can still be sensitive. Minimization reduces exposure but does not remove legal or security obligations."},
 {id:"responsibility",number:"04",title:"Responsibility matrix",category:"Trust",summary:"Clear ownership across client, shared, and Adaptive Engine vendor responsibilities.",audiences:["Product owner","Privacy reviewer","Pilot team"],lanes:[{title:"Client owns",tone:"client",nodes:["Content + answer keys","Opaque IDs","Grading","Server-side key","Fallback","Learner access"]},{title:"Shared",tone:"shared",nodes:["Metadata contract","Curriculum review","Privacy review","Pilot metrics","Incident planning"]},{title:"Vendor owns",tone:"engine",nodes:["Isolated tenants","Scoped credentials","Minimal evidence","Versioned decisions","Monitoring + recovery"]}],steps:["Assign one accountable owner per responsibility","Document shared decisions before pilot","Test both client fallback and vendor recovery","Review responsibilities during offboarding"],takeaway:"The privacy boundary is only reliable when operational responsibilities are equally explicit."},
 {id:"onboarding",number:"05",title:"Client onboarding flow",category:"Operations",summary:"From first discovery through test tenant, shadow mode, limited pilot and paid expansion.",audiences:["Product owner","Engineer","Privacy reviewer","Pilot team"],lanes:[{title:"Qualify",tone:"external",nodes:["Discovery","Problem fit","Technical readiness"]},{title:"Approve",tone:"shared",nodes:["Scope + metadata","Privacy + security","Success criteria"]},{title:"Integrate",tone:"client",nodes:["Test tenant","Catalogue sync","Synthetic tests","Shadow mode"]},{title:"Launch",tone:"engine",nodes:["Production tenant","Limited pilot","Monitor","Expand or stop"]}],steps:["Pause if the client lacks technical readiness","Confirm an approval path before credentials","Validate metadata before learner testing","Run synthetic and shadow tests","Launch a limited authorized pilot","Expand only when evidence supports it"],takeaway:"Onboarding is a gated evidence process, not simply issuing an API key."},
 {id:"curriculum",number:"06",title:"Curriculum and item mapping",category:"Content",summary:"Versioned provincial packages, prerequisite graphs, publisher extensions, and multi-concept item mappings.",audiences:["Product owner","Engineer","Curriculum specialist"],lanes:[{title:"Official graph",tone:"shared",nodes:["Jurisdiction","Version","Subject","Grade / course","Strand","Expectation","Concept"]},{title:"Tenant extension",tone:"client",nodes:["Publisher package","Custom concepts","Local terminology"]},{title:"Client item bank",tone:"external",nodes:["Primary mapping","Secondary mapping","Mapping weight","Tenant-only mapping"]}],steps:["Choose a reviewed jurisdiction and version","Import an acyclic official hierarchy","Keep tenant extensions separate","Allow several concept mappings","Require at most one primary concept per curriculum"],takeaway:"Canada is represented as separate jurisdiction packages—not one fictional national curriculum."},
 {id:"recommendation",number:"07",title:"Recommendation decision",category:"Runtime",summary:"How authentication, filters, session goals, scaffolding, weakness, freshness, and fallback produce a decision.",audiences:["Engineer","Curriculum specialist","Pilot team"],lanes:[{title:"Gate",tone:"shared",nodes:["Authenticate","Apply tenant filters","Eligible bank?"]},{title:"Choose goal",tone:"engine",nodes:["Diagnostic","Practice","Remediation","Review"]},{title:"Target",tone:"client",nodes:["Least evidence","Weakest skill","Scaffold after misses","Least recently practised"]},{title:"Select + explain",tone:"external",nodes:["Difficulty band","Fresh item","Fallback ladder","Record reason + version"]}],steps:["Reject missing scope","Return bank_exhausted when filters leave nothing","Choose target based on session goal","Prefer suitable fresh content","Use an explicit fallback ladder","Append the decision before returning it"],takeaway:"Every recommendation follows a visible decision path and records why it happened."},
 {id:"idempotency",number:"08",title:"Answer event and idempotency",category:"Runtime",summary:"How a graded event updates mastery exactly once—even when networks retry requests.",audiences:["Engineer","Privacy reviewer","Pilot team"],lanes:[{title:"Validate",tone:"client",nodes:["events:write scope","Learner ID","Item ID","Outcome + timestamp"]},{title:"Replay gate",tone:"shared",nodes:["Lock idempotency key","Existing event?","Payload matches?"]},{title:"Update",tone:"engine",nodes:["Load item + state","Calculate mastery","Update evidence","Append immutable event"]},{title:"Return",tone:"external",nodes:["replayed: true","409 conflict","Updated mastery"]}],steps:["Authenticate and validate","Lock tenant plus idempotency key","Replay identical events safely","Reject conflicting key reuse","Commit state and event atomically"],takeaway:"The idempotency key behaves like a receipt number: one learner attempt can affect mastery only once."},
 {id:"isolation",number:"09",title:"Tenant isolation",category:"Trust",summary:"How scoped keys, tenant predicates, shared curricula, and RLS prevent cross-client access.",audiences:["Engineer","Privacy reviewer"],lanes:[{title:"Client A",tone:"client",nodes:["Backend A","API key A","Tenant A predicate"]},{title:"Gateway",tone:"shared",nodes:["Hash lookup","Scope check","Tenant binding"]},{title:"Client B",tone:"external",nodes:["Backend B","API key B","Tenant B predicate"]},{title:"Database defence",tone:"engine",nodes:["Tenant rows","Official curricula","RLS, no public policies"]}],steps:["Bind every credential to one tenant","Add the tenant predicate to every query","Reject cross-tenant identifiers","Permit shared read-only official curricula","Use RLS as defence in depth"],takeaway:"Application predicates are primary isolation; database RLS is an additional barrier—not a substitute."},
 {id:"deployment",number:"10",title:"Canadian operational boundary",category:"Operations",summary:"The complete residency surface across service, databases, recovery, telemetry, keys, releases, and support.",audiences:["Engineer","Privacy reviewer","Investor"],lanes:[{title:"Client infrastructure",tone:"client",nodes:["Browser","Client API","Accounts + content","Client logs"]},{title:"Encrypted transit",tone:"shared",nodes:["TLS","HTTPS load balancer"]},{title:"Canadian region",tone:"engine",nodes:["Stateless service","Primary database","Replica + backup","Logs + traces","KMS + secrets"]},{title:"Controlled operations",tone:"external",nodes:["Approved CI/CD","Audited support","Incident response"]}],steps:["Map every storage and processing location","Verify replicas and backups","Keep telemetry and keys in scope","Audit support access","Contractually review subprocessors"],takeaway:"A Canadian database alone does not prove Canadian residency for the service."},
 {id:"shadow",number:"11",title:"Shadow-mode rollout",category:"Evidence",summary:"Compare the current selection logic and engine recommendation without changing what learners see.",audiences:["Product owner","Engineer","Investor","Pilot team"],lanes:[{title:"Production path",tone:"client",nodes:["Existing selector","Learner-facing item"]},{title:"Parallel shadow",tone:"engine",nodes:["Engine request","Reason + version","No learner exposure"]},{title:"Evaluation",tone:"shared",nodes:["Store both decisions","Compare latency","Review disagreement","Assess outcomes"]},{title:"Gate",tone:"external",nodes:["Enable small cohort","Revise","Stop"]}],steps:["Request both decisions in parallel","Show only the existing production item","Store approved comparison context","Review predefined criteria","Enable only a small cohort after acceptance"],takeaway:"Shadow mode creates evidence without letting an unvalidated policy control learner experiences."},
 {id:"evolution",number:"12",title:"Product evolution",category:"Roadmap",summary:"Separate today’s foundation, validation work, research roadmap, and possible future assessment platform.",audiences:["Product owner","Investor"],lanes:[{title:"Current",tone:"client",nodes:["Multi-tenant API","Metadata","Idempotent events","Transparent mastery"]},{title:"Validate",tone:"shared",nodes:["Design partners","Historical replay","Calibration","Trust evidence"]},{title:"Research",tone:"engine",nodes:["Prerequisite routing","Memory model","Model comparison","Controlled rollout"]},{title:"Possible future",tone:"external",nodes:["Authoring","Accessible player","Rich scoring","LTI + QTI"]}],steps:["Harden the current foundation","Validate in real workflows","Research only evidence-backed model changes","Enter assessment-platform scope only after market proof"],takeaway:"Future platform expansion is optional. Validation is the bridge—not a feature backlog."},
 {id:"incident",number:"13",title:"Incident and support flow",category:"Operations",summary:"Triage, contain, preserve, diagnose, fix, verify, restore, review, and close safely.",audiences:["Engineer","Privacy reviewer","Pilot team"],lanes:[{title:"Signal",tone:"risk",nodes:["Alert","Client report","Learner harm concern"]},{title:"Triage + contain",tone:"shared",nodes:["Classify severity","Revoke key","Suspend tenant","Preserve evidence"]},{title:"Resolve",tone:"engine",nodes:["Reproduce safely","Fix root cause","Regression test","Controlled restore"]},{title:"Learn",tone:"external",nodes:["Notify as required","Joint review","Preventive actions","Owners + dates"]}],steps:["Classify security, privacy, availability, integrity or recommendation issue","Contain material risk immediately","Use synthetic or minimized data to reproduce","Verify isolation and recovery","Document preventive actions"],takeaway:"Incident handling is part of the product architecture, not an operations appendix."},
 {id:"research",number:"14",title:"Research feedback loop",category:"Evidence",summary:"Pre-register, instrument, test, replay, shadow, pilot, review, decide, roll out, and monitor.",audiences:["Product owner","Engineer","Investor","Pilot team"],lanes:[{title:"Hypothesis",tone:"client",nodes:["Pre-register","Define outcome","Version instrumentation"]},{title:"Evidence ladder",tone:"shared",nodes:["Synthetic tests","Historical replay","Shadow mode","Prospective pilot"]},{title:"Review",tone:"engine",nodes:["Learning","Fairness","Privacy","Operations"]},{title:"Decision",tone:"external",nodes:["Versioned rollout","Reject or revise","Monitor"]}],steps:["Define the hypothesis before viewing results","Climb from synthetic to prospective evidence","Review more than immediate correctness","Roll out by tenant and version","Feed monitoring into the next hypothesis"],takeaway:"The engine improves through controlled evidence loops—not silent model changes."},
 {id:"summary",number:"15",title:"One-page operating loop",category:"Summary",summary:"The entire system in nine memorable steps from data boundary to continuous validation.",audiences:["Product owner","Engineer","Privacy reviewer","Curriculum specialist","Investor","Pilot team"],lanes:[{title:"Prepare",tone:"client",nodes:["Client keeps content","Create tenant + key","Sync metadata"]},{title:"Recommend",tone:"engine",nodes:["Request with pseudonym","Return item + reason"]},{title:"Learn",tone:"shared",nodes:["Client grades","Report idempotent outcome","Update mastery"]},{title:"Improve",tone:"external",nodes:["Monitor","Validate","Repeat"]}],steps:["Client keeps content, identity and grading","Vendor creates isolated tenant and scoped key","Client synchronizes metadata","Client requests next item","Engine returns explainable decision","Client displays and grades","Client reports outcome with idempotency key","Engine updates mastery and evidence","Both parties monitor and improve"],takeaway:"Minimal data crosses the boundary; explainable decisions and evidence come back."},
];
const audiences:Audience[]=["All","Product owner","Engineer","Privacy reviewer","Curriculum specialist","Investor","Pilot team"];

export function ArchitectureAtlas(){
 const [audience,setAudience]=useState<Audience>("All");const [activeId,setActiveId]=useState("ecosystem");const [details,setDetails]=useState(true);const visible=useMemo(()=>diagrams.filter(d=>audience==="All"||d.audiences.includes(audience)),[audience]);const active=visible.find(d=>d.id===activeId)??visible[0]??diagrams[0];
 const pickAudience=(value:Audience)=>{setAudience(value);const first=diagrams.find(d=>value==="All"||d.audiences.includes(value));if(first)setActiveId(first.id)};
 return <>
  <header className="section-header"><div className="eyebrow"><span/>Interactive systems map</div><h1>Adaptive Engine architecture atlas.</h1><p>Explore the complete ecosystem, runtime, privacy boundary, curriculum graph, operational controls, rollout, and research loops—tailored to the audience in the room.</p></header>
  <section className="atlas-hero"><div><span>Core architectural promise</span><h2>The client owns the learning experience.<br/>The engine owns the next-practice decision.</h2><p>Only a private client backend calls the engine. Content, answer keys, identity, grading, and official records remain on the client side.</p></div><div className="boundary-mini"><article><i>CLIENT</i><strong>Content + identity</strong><span>grades locally</span></article><b>metadata<br/>＋ outcomes <em>→</em><br/><em>←</em> decisions</b><article><i>ENGINE</i><strong>Mastery + selection</strong><span>explains every choice</span></article></div></section>
  <section className="atlas-controls"><div><span>Show diagrams for</span>{audiences.map(a=><button className={audience===a?"active":""} key={a} onClick={()=>pickAudience(a)}>{a}</button>)}</div><label><input type="checkbox" checked={details} onChange={e=>setDetails(e.target.checked)}/><i/><span>Show step details</span></label></section>
  <div className="atlas-layout"><nav className="atlas-library" aria-label="Architecture diagrams">{visible.map(d=><button className={active.id===d.id?"active":""} key={d.id} onClick={()=>setActiveId(d.id)}><i>{d.number}</i><span><small>{d.category}</small><strong>{d.title}</strong></span><b>→</b></button>)}</nav>
   <section className="atlas-stage"><header><div><span>{active.number} · {active.category}</span><h2>{active.title}</h2><p>{active.summary}</p></div><button onClick={()=>navigator.clipboard.writeText(`${active.title}\n\n${active.summary}\n\n${active.steps.map((s,i)=>`${i+1}. ${s}`).join("\n")}\n\nKey takeaway: ${active.takeaway}`)}>Copy outline</button></header>
    <div className={`atlas-canvas lanes-${active.lanes.length}`}>{active.lanes.map((lane,laneIndex)=><div className={`atlas-lane lane-${lane.tone}`} key={lane.title}><header><i>{String(laneIndex+1).padStart(2,"0")}</i><strong>{lane.title}</strong></header><div>{lane.nodes.map((node,index)=><article key={node}><span>{node}</span>{index<lane.nodes.length-1&&<b>↓</b>}</article>)}</div>{laneIndex<active.lanes.length-1&&<em className="lane-connector">→</em>}</div>)}</div>
    <div className="atlas-takeaway"><i>◆</i><div><span>What to remember</span><strong>{active.takeaway}</strong></div></div>
    {details&&<div className="atlas-steps"><header><span>Walkthrough</span><strong>{active.steps.length} steps</strong></header><ol>{active.steps.map((step,index)=><li key={step}><i>{String(index+1).padStart(2,"0")}</i><span>{step}</span></li>)}</ol></div>}
   </section>
  </div>
  <section className="atlas-legend"><div><i className="legend-client"/><span>Client controlled</span></div><div><i className="legend-engine"/><span>Adaptive Engine</span></div><div><i className="legend-shared"/><span>Shared responsibility</span></div><div><i className="legend-external"/><span>People or external system</span></div><div><i className="legend-risk"/><span>Blocked or risk boundary</span></div></section>
  <section className="atlas-audience-guide"><header><span>Present the right story</span><h2>Diagram selection guide</h2></header>{[["Client product owner","Ecosystem · Practice loop · Responsibilities · Onboarding"],["Client engineer","Practice loop · Idempotency · Isolation · Deployment"],["Privacy reviewer","Privacy boundary · Isolation · Deployment · Incident flow"],["Curriculum specialist","Curriculum mapping · Recommendation decision"],["Investor or grant reviewer","Ecosystem · Product evolution · Research loop"],["Pilot team","Onboarding · Shadow mode · Incident flow · Summary"]].map(([role,list])=><article key={role}><strong>{role}</strong><span>{list}</span></article>)}</section>
 </>;
}
