export type DocumentCategory = "Corporate & legal standing" | "Employment & payroll" | "Financial" | "R&D project" | "Reimbursement substantiation" | "Business context";

export type IrapDocument = {
  id: string;
  title: string;
  category: DocumentCategory;
  description: string;
  generated?: boolean;
  sections?: Array<{ heading: string; body: string }>;
};

const company = "Opyjo Inc.";
const project = "Adaptive Learning Decision Engine R&D Project";

const baseDocuments: IrapDocument[] = [
  { id: "articles", title: "Articles and Certificate of Incorporation", category: "Corporate & legal standing", description: "Official incorporation records." },
  { id: "standing", title: "Annual filings / proof of good standing", category: "Corporate & legal standing", description: "Current official status after overdue filings are resolved." },
  { id: "cra-accounts", title: "Business Number and CRA account confirmations", category: "Corporate & legal standing", description: "BN and active CRA program accounts." },
  { id: "ownership", title: "Shareholder register / ownership structure", category: "Corporate & legal standing", description: "Ownership and confirmation of parent or subsidiary relationships." },
  { id: "ip", title: "Trademark and IP registration filings", category: "Corporate & legal standing", description: "Filed or registered intellectual-property evidence, when available." },
  { id: "rp", title: "CRA payroll (RP) registration", category: "Employment & payroll", description: "Payroll program account confirmation." },
  { id: "employment", title: "Signed employment agreement and job description", category: "Employment & payroll", description: "Oluwamayomikun's executed employment and role documents." },
  { id: "td1", title: "Federal and Ontario TD1 forms", category: "Employment & payroll", description: "Completed employee tax-credit forms." },
  { id: "pay-records", title: "Payroll records and pay stubs", category: "Employment & payroll", description: "Evidence of active T4 employment." },
  { id: "t4", title: "T4 slips", category: "Employment & payroll", description: "Annual slips once issued." },
  { id: "hours", title: "Records of hours and wages", category: "Employment & payroll", description: "Labour evidence supporting eligible salary costs." },
  {
    id: "company-project-brief", title: "Company and project brief", category: "Business context", generated: true, description: "Concise two-page decision brief for advisors and reviewers.",
    sections: [
      { heading: "Company", body: "Opyjo Inc. is a Canadian technology company developing a standalone adaptive-learning decision service. Complete before external use: incorporation jurisdiction/date [INPUT], CRA Business Number [INPUT], operating address [INPUT], ownership [INPUT], FTE count [INPUT], current revenue [INPUT], and senior executive [INPUT]." },
      { heading: "Opportunity", body: "Learning applications commonly rely on fixed sequences or internal rules. Building credible adaptation requires learner modelling, item calibration, experimentation, privacy engineering, and longitudinal outcome evidence. Opyjo’s engine lets an existing learning product request the next item without transferring question content, answer keys, or direct learner identity." },
      { heading: "Verified starting point", body: "The repository contains a TypeScript/Fastify/PostgreSQL multi-tenant API, adaptive-v1 learner model and selection policy, scoped hashed API keys, idempotent answer recording, algorithm-versioned audit events, RLS-enabled tables, OpenAPI 3.1, Docker and Railway configuration, and Brightwick integration guidance. Sixteen automated tests pass; three database integration tests require a configured test database. Build and lint pass." },
      { heading: "R&D project", body: "The proposed 10-month project investigates four uncertainties: reliable learner inference under sparse data; safe empirical correction of item-difficulty priors; measurable durable learning improvement over a baseline; and cross-tenant usefulness across different curricula and usage patterns. Routine deployment, marketing, administration, and unrelated product work are outside the R&D centre." },
      { heading: "Outputs and economic case", body: "Planned outputs are a selected confidence-aware learner model, calibrated item pipeline, controlled outcome report, external-tenant validation, and hardened commercialization playbook. Complete: project dates [INPUT], total cost $[INPUT], requested contribution $[INPUT], company contribution $[INPUT], Canadian jobs [INPUT], three-year revenue $[INPUT], export revenue $[INPUT], and design partners [INPUT]." },
      { heading: "Immediate decision requested", body: "Opyjo seeks advisor guidance on project fit, technical scope, eligible Canadian labour and cost treatment, evidence expectations, contribution range, and the steps required to develop a formal proposal. Attach the detailed R&D proposal, budget, cash flow, management profiles, financial statements, and partner evidence." },
    ],
  },
  {
    id: "technical-baseline", title: "Technical baseline report", category: "R&D project", generated: true, description: "Dated before-state against which technical advancement will be measured.",
    sections: [
      { heading: "Baseline identity and reproducibility", body: "Baseline name: adaptive-v1. Repository: adaptive-engine. Baseline date: July 12, 2026. Reference commit: [INPUT CURRENT COMMIT AT PROJECT START]. Runtime: Node.js 24+, TypeScript 5.9, Fastify 5, PostgreSQL. Record package-lock checksum, migration version, environment, dataset version, configuration, and command outputs so the baseline can be reproduced." },
      { heading: "Current mastery model", body: "New skill state begins at 0.5. Each answer applies mastery = clamp01(mastery + 0.15 x difficultyWeight x (outcome - mastery)). Correct answers receive more weight at greater difficulty; incorrect answers receive more weight at lower difficulty. State retains attempts, consecutive wrong answers, and last-practised time. This is an engineered heuristic and is not yet empirically calibrated as a probability of mastery." },
      { heading: "Current selection model", body: "Priority: scaffold the most recently practised skill after at least two consecutive errors; otherwise target the weakest skill below 0.8; otherwise spiral the least recently practised skill. Mastery maps to difficulty bands. Items from the last 30 answers or 14 days are avoided where possible. An explicit relaxation ladder returns fallback when the ideal pool is empty. Seeded tie-breaking makes equal state/history reproducible." },
      { heading: "Current system controls", body: "The API accepts metadata-only item records, opaque learner IDs, and correct/incorrect events. Keys are scoped, hashed, expirable, and revocable. Tenant ID leads queries, keys, references, and indexes. RLS is enabled with no policies for non-owner paths. Answer events are transactionally idempotent and append-only; recommendation decisions are versioned and audited." },
      { heading: "Verification results", body: "As reviewed July 12, 2026: 16 automated tests passed; 3 PostgreSQL integration tests were skipped without TEST_DATABASE_URL; TypeScript build and ESLint passed. Before project start, attach timestamped CI output, full database integration output, migration result, dependency/security scan, and environment record." },
      { heading: "Baseline measurement table", body: "METRIC | BASELINE | METHOD | DATASET | OWNER\nLog-loss/Brier score | [INPUT] | replay evaluation | [INPUT] | [INPUT]\nCalibration error | [INPUT] | reliability analysis | [INPUT] | [INPUT]\nCold-start accuracy | [INPUT] | first N outcomes | [INPUT] | [INPUT]\nFallback rate | [INPUT]% | selection events | [INPUT] | [INPUT]\nRecommendation coverage | [INPUT]% | eligible requests | [INPUT] | [INPUT]\np50/p95 latency | [INPUT]/[INPUT] ms | load test | [INPUT] | [INPUT]\nError rate | [INPUT]% | monitored requests | [INPUT] | [INPUT]." },
      { heading: "Known limitations and evidence gaps", body: "No completed production deployment, managed-database restore drill, load/soak result, penetration test, Brightwick shadow comparison, empirical item calibration, causal outcome experiment, fairness analysis, or external-tenant result is proven by the repository. The baseline report must preserve these gaps because they define the proposed technical investigation." },
      { heading: "Approval", body: "Prepared by [INPUT], reviewed by [INPUT], date [INPUT], baseline commit [INPUT], evidence folder [INPUT]. Any later correction must create a new version without overwriting this approved baseline." },
    ],
  },
  {
    id: "experiment-plan", title: "R&D experiment and evidence plan", category: "R&D project", generated: true, description: "Pre-registered hypotheses, methods, measures, and decision rules.",
    sections: [
      { heading: "Evidence governance", body: "Every investigation receives an experiment ID, hypothesis, technical uncertainty, owner, code commit, dataset version, protocol version, start/end date, eligibility work package, time records, and signed decision. Raw pseudonymous events are immutable; derived datasets and analyses are versioned. Results—including null and adverse results—are retained." },
      { heading: "EXP-01 Sparse-data learner state", body: "Hypothesis: a confidence-aware alternative will improve held-out prediction and calibration during the first [INPUT] observations without unacceptable instability. Compare adaptive-v1 EWMA, Elo/IRT-inspired, and confidence-weighted alternatives. Predefine cohorts, train/validation split, leakage controls, missing-data treatment, random seeds, and minimum sample. Primary measures: log-loss/Brier score and calibration error. Secondary: ranking stability and observations-to-stability. Decision threshold [INPUT]." },
      { heading: "EXP-02 Empirical item difficulty", body: "Hypothesis: shrinkage-based behavioural calibration will reduce held-out prediction error versus tenant 1-5 priors while remaining stable at low volume. Define learner-state conditioning, tenant/global pooling, minimum samples, confidence intervals, drift windows, and human-review rules. Primary: prior-versus-observed error and held-out improvement. Guardrails: update volatility, subgroup divergence, and false drift alerts. Decision threshold [INPUT]." },
      { heading: "EXP-03 Durable learning outcome", body: "Hypothesis: the selected adaptive policy improves delayed retention or reduces time-to-mastery relative to an agreed baseline. Use stable learner assignment, intention-to-treat analysis, pre-defined exclusions, sample-size rationale, delayed review window, stopping rules, and locked outcomes. Guardrails: completion, error streak, fallback, latency, incident rate, and subgroup harm. Do not change primary outcomes after observing results." },
      { heading: "EXP-04 Cross-tenant validation", body: "Hypothesis: the engine can meet usefulness, isolation, reliability, and onboarding targets across at least [INPUT] external tenants with different banks and taxonomies. Measures: mapping defects, eligible-bank coverage, integration days, fallback, latency, error rate, idempotent retry, isolation-test result, deletion/export completion, and partner acceptance. Define minimum event volume and pass thresholds [INPUT]." },
      { heading: "Evidence register", body: "EXPERIMENT | ARTIFACT | LOCATION | HASH/VERSION | OWNER | REVIEW DATE\n[INPUT] Protocol | [INPUT] | [INPUT] | [INPUT] | [INPUT]\n[INPUT] Dataset specification | [INPUT] | [INPUT] | [INPUT] | [INPUT]\n[INPUT] Analysis notebook/report | [INPUT] | [INPUT] | [INPUT] | [INPUT]\n[INPUT] Test output | [INPUT] | [INPUT] | [INPUT] | [INPUT]\n[INPUT] Decision record | [INPUT] | [INPUT] | [INPUT] | [INPUT]." },
      { heading: "Decision record", body: "At each gate record observed results, uncertainty intervals, unexpected behaviour, limitations, residual risk, budget/time variance, and decision: promote, revise, repeat, pause, or rollback. Technical approver [INPUT]; project owner [INPUT]; privacy/security reviewer [INPUT]; finance reviewer [INPUT]. Material scope changes require written IRAP approval where applicable." },
    ],
  },
  {
    id: "brightwick-shadow-report", title: "Brightwick shadow-mode report", category: "R&D project", generated: true, description: "Operational and technical evidence from the first integration.",
    sections: [
      { heading: "Report status", body: "STATUS: TEMPLATE - NOT YET EVIDENCE OF A COMPLETED SHADOW RUN. Reporting period [INPUT]. Brightwick version [INPUT]. Adaptive-engine commit/model [INPUT]. Environments [INPUT]. Owners [INPUT]. The learner experience remained controlled by [existing logic / engine] during this period [INPUT]." },
      { heading: "Integration implemented", body: "Confirm with evidence: test tenant and least-privilege server-only key; stable opaque learner mapping; bulk item-metadata sync; create/edit/retire synchronization; shadow next-item call; outcome posting using answer UUID as idempotency key; timeout/5xx fallback; 429 backoff; feature flag; rollback path; monitoring; and prohibition on content, answer keys, names, emails, birthdates, or raw auth tokens." },
      { heading: "Population and data quality", body: "Learners [INPUT]; requests [INPUT]; answer events [INPUT]; active items [INPUT]; skills [INPUT]; grade bands [INPUT]; date range [INPUT]; missing metadata [INPUT]%; invalid/rejected requests [INPUT]; duplicate retries [INPUT]; PII scan result [INPUT]. Explain exclusions, outages, backfills, and changes during the period." },
      { heading: "Comparison results", body: "METRIC | EXISTING LOGIC | ENGINE | DIFFERENCE | TARGET\nRecommendation agreement | [INPUT] | [INPUT] | [INPUT] | descriptive\nEligible-bank coverage | [INPUT]% | [INPUT]% | [INPUT] | >[INPUT]%\nFallback rate | n/a | [INPUT]% | n/a | <[INPUT]%\nError-streak response | [INPUT] | [INPUT] | [INPUT] | [INPUT]\np50/p95 latency | [INPUT] | [INPUT] | [INPUT] | <[INPUT] ms\nRequest error rate | [INPUT]% | [INPUT]% | [INPUT] | <[INPUT]%\nIdempotent replay success | n/a | [INPUT]% | n/a | 100%." },
      { heading: "Technical findings", body: "Document observed mapping defects, surprising decisions, cold-start behaviour, repeated-error scaffolding, recency handling, difficulty mismatch, fallback reasons, mastery divergence, performance bottlenecks, retry conflicts, tenant-isolation results, and operational incidents. Link each finding to event/query evidence and an issue or decision record." },
      { heading: "Decision and next step", body: "Decision: continue shadow / limited test cohort / revise / pause [INPUT]. Rationale [INPUT]. Required corrections [INPUT]. Learner-facing ramp [INPUT]%. Success and rollback thresholds [INPUT]. Approvals: technical [INPUT], product [INPUT], privacy/security [INPUT], date [INPUT]." },
    ],
  },
  {
    id: "customer-interview-report", title: "Customer discovery and interview report", category: "Business context", generated: true, description: "Primary-market evidence and validated buying requirements.",
    sections: [
      { heading: "Research objective", body: "Determine whether EdTech applications and tutoring operators have a material personalization problem, sufficient content/data readiness, authority and budget to purchase an adaptive decision service, acceptable integration/security requirements, and willingness to enter a pilot. Target 5-10 qualified interviews across clearly defined segments." },
      { heading: "Interview protocol", body: "Ask about current sequencing and learner-outcome workflow; measurable cost of the problem; internal team and alternatives attempted; content and skill metadata; learner/event volume; privacy/security/procurement; desired outcomes; integration capacity; decision makers; budget; timeline; pilot success; price response; objections; and next commitment. Avoid leading questions and do not present the solution until the current state is understood." },
      { heading: "Interview evidence table", body: "ID | DATE | COMPANY/SEGMENT | ROLE | PROBLEM SEVERITY | CURRENT ALTERNATIVE | DATA READINESS | BUYER/BUDGET | TIMELINE | PRICE RESPONSE | COMMITMENT | EVIDENCE LINK\n01 | [INPUT] | [INPUT] | [INPUT] | [INPUT] | [INPUT] | [INPUT] | [INPUT] | [INPUT] | [INPUT] | [INPUT] | [INPUT]\nAdd one row per interview. Retain consent and notes; do not expose confidential identities externally without permission." },
      { heading: "Findings by hypothesis", body: "H1 fixed sequencing is a priority problem: supported/not supported [INPUT], evidence [INPUT]. H2 customers prefer metadata-only integration: [INPUT]. H3 auditability/outcome evidence affects purchase: [INPUT]. H4 buyer will pay onboarding plus usage/annual fees: [INPUT]. H5 integration can complete within [INPUT] days: [INPUT]. Report contrary evidence and segment differences." },
      { heading: "Commercial implications", body: "Selected beachhead [INPUT]; excluded segments [INPUT]; buyer [INPUT]; user [INPUT]; required features/controls [INPUT]; pilot offer [INPUT]; validated price range $[INPUT]; expected sales cycle [INPUT]; partner-acquisition channel [INPUT]; changes to roadmap [INPUT]. Distinguish interview statements from signed commitments and paid behaviour." },
      { heading: "Appendices and approval", body: "Append interview guide, anonymized notes, quotation excerpts with permission, source links, scoring rubric, outreach list, and commitment documents. Prepared by [INPUT], reviewed by [INPUT], version/date [INPUT]." },
    ],
  },
  {
    id: "design-partner-letter", title: "Design-partner letter of interest", category: "Business context", generated: true, description: "Non-binding evidence template for prospective pilot partners.",
    sections: [
      { heading: "Parties and status", body: "Date [INPUT]. To Opyjo Inc. From [PARTNER LEGAL NAME], [ADDRESS]. This letter records the parties’ current interest in evaluating Opyjo’s adaptive-learning decision service. Except for confidentiality, data protection, publicity, or other clauses explicitly stated as binding, it is non-binding and does not create a purchase obligation. Obtain legal review before use." },
      { heading: "Partner context and need", body: "[PARTNER] operates [PRODUCT/SERVICE] for [CUSTOMERS/LEARNERS]. Its current approach to item sequencing/personalization is [INPUT]. The business or learning problem it wishes to assess is [INPUT], currently measured by [INPUT]. The partner believes an evaluation is strategically relevant because [INPUT]." },
      { heading: "Proposed evaluation", body: "Subject to a definitive agreement, the partner is interested in: technical discovery; metadata and skill-taxonomy assessment; sandbox integration; shadow-mode comparison; and/or controlled pilot [SELECT]. Expected period [INPUT]. Estimated items [INPUT], skills [INPUT], learners [INPUT], and monthly events [INPUT]. No question content, answer keys, or direct learner identity will be provided to the engine." },
      { heading: "Responsibilities and success evidence", body: "Opyjo would provide the API, onboarding, documentation, model/audit outputs, support, and agreed reporting. The partner would provide approved metadata, opaque IDs, graded outcomes, integration resources, and authorized feedback. Candidate success measures: integration days, eligible-bank coverage, reliability/latency, operational fit, delayed retention/time-to-mastery, and commercial value. Final thresholds [INPUT]." },
      { heading: "Commercial intent", body: "If the evaluation meets agreed success criteria, the partner is willing to discuss [paid pilot / production subscription / annual agreement] within [INPUT] days. Indicative budget authority or range, if the partner is comfortable stating it: $[INPUT]. Decision makers [INPUT]. Procurement/security requirements [INPUT]. This paragraph should reflect the partner’s actual position and must not be exaggerated." },
      { heading: "Signatures", body: "For [PARTNER]: name [INPUT], title [INPUT], signature [INPUT], date [INPUT]. For Opyjo Inc.: name [INPUT], title [INPUT], signature [INPUT], date [INPUT]. Confidentiality/publicity treatment [INPUT]. Evidence-file location [INPUT]." },
    ],
  },
  {
    id: "canadian-benefit", title: "Canadian economic-benefit calculation", category: "Business context", generated: true, description: "Quantified jobs, capability, IP, revenue, and export impact.",
    sections: [
      { heading: "Method and baseline", body: "Reporting base date [INPUT]. Use only benefits reasonably attributable to the project and commercialization plan. State sources, formulas, timing, probability weighting, and whether figures are commitments, base-case forecasts, or aspirations. Avoid counting the same job, revenue, or investment twice across programs." },
      { heading: "Employment calculation", body: "METRIC | BASELINE | PROJECT END | YEAR 1 | YEAR 2 | YEAR 3 | SOURCE\nCanadian FTEs | [INPUT] | [INPUT] | [INPUT] | [INPUT] | [INPUT] | payroll/forecast\nTechnical/R&D FTEs | [INPUT] | [INPUT] | [INPUT] | [INPUT] | [INPUT] | staffing plan\nJobs created | 0 | [INPUT] | [INPUT] | [INPUT] | [INPUT] | approved hires\nJobs retained | [INPUT] | [INPUT] | [INPUT] | [INPUT] | [INPUT] | management basis\nCanadian payroll | $[INPUT] | $[INPUT] | $[INPUT] | $[INPUT] | $[INPUT] | projections." },
      { heading: "Revenue and export calculation", body: "Canadian adaptive-engine revenue: Year 1 $[INPUT], Year 2 $[INPUT], Year 3 $[INPUT]. Export revenue: $[INPUT], $[INPUT], $[INPUT]. Customers: [INPUT]. Annual contract/usage assumptions [INPUT]. Probability-adjusted three-year incremental revenue = sum of scenario revenue attributable to the project x documented probability. Reconcile to financial projections and market pipeline." },
      { heading: "Innovation capacity and IP", body: "New Canadian capabilities: sparse-data learner modelling, empirical calibration, controlled learning-outcome experimentation, privacy/security engineering, and multi-tenant product operations. Evidence: trained personnel [INPUT], model/experiment artifacts [INPUT], Canadian-controlled source code/IP [INPUT], registrations [INPUT], partner knowledge transfer [INPUT], and future R&D investment $[INPUT]." },
      { heading: "Wider Canadian benefits", body: "Describe benefits to Canadian EdTech and tutoring partners, supplier spend, improved access to adaptive capability, export competitiveness, and credible learner outcomes. Quantify Canadian supplier spend $[INPUT], partners [INPUT], trainees [INPUT], and regional/sector benefit [INPUT]. Do not claim educational outcomes before the controlled evidence exists." },
      { heading: "Attribution, risks, and approval", body: "Key dependencies: technical success, partner recruitment, financing, procurement, pricing, and event volume. Provide downside/base/upside benefit scenarios and the action taken if targets slip. Prepared by [INPUT], financial review [INPUT], technical review [INPUT], approval/date [INPUT], supporting workbook [INPUT]." },
    ],
  },
  {
    id: "team-profiles", title: "Management and technical team profiles", category: "Business context", generated: true, description: "Reviewer-focused capability, responsibility, and capacity profiles.",
    sections: [
      { heading: "Team summary", body: "Provide a one-page organization view showing senior executive, project owner, technical lead, R&D employees, finance/claim owner, commercialization owner, privacy/security accountability, and external specialists. State reporting lines, decision rights, Canadian work location, employment status, and percentage of time committed." },
      { heading: "Senior executive / project sponsor", body: "Name [INPUT], title [INPUT], location [INPUT], employment status [INPUT], project commitment [INPUT]%. Relevant company-building, financing, customer, education, and technology experience [INPUT]. Project responsibilities: corporate authority, IRAP relationship, financing, scope approval, commercialization, and Canadian-benefit delivery. Evidence: resume/LinkedIn [INPUT], prior outcomes [INPUT]." },
      { heading: "Technical lead", body: "Name [INPUT], title [INPUT], location [INPUT], commitment [INPUT]%. Relevant experience in TypeScript/Node, PostgreSQL, APIs, experimentation, learning models, security/privacy, and production systems [INPUT]. Responsibilities: technical hypotheses, architecture, experiment approval, model decisions, code review, evidence integrity, risk, and milestone acceptance. Capability gaps and mitigation [INPUT]." },
      { heading: "R&D software developer", body: "Oluwamayomikun [CONFIRM FULL LEGAL NAME], title [INPUT], Ontario, T4 status [INPUT], start date [INPUT], commitment [INPUT]%. Education and relevant implementation/testing/data experience [INPUT]. Responsibilities by approved work package [INPUT]. Separate experimental work from routine product tasks. Attach signed job description, resume, employment agreement, and payroll evidence in the source vault." },
      { heading: "Finance and claims owner", body: "Name [INPUT], internal/external status [INPUT], qualifications [INPUT]. Responsibilities: budget version control, payroll/timesheet reconciliation, cash forecast, cost eligibility confirmation, stacking, claim support, document retention, variance reporting, and contribution-agreement compliance. Backup coverage [INPUT]." },
      { heading: "Commercialization and partner owner", body: "Name [INPUT], qualifications [INPUT], commitment [INPUT]%. Responsibilities: market research, interview evidence, design-partner funnel, pilot definition, pricing validation, procurement requirements, conversion, revenue forecast, and partner reporting. Targets [INPUT]." },
      { heading: "Capacity and gap plan", body: "ROLE/CAPABILITY | CURRENT COVERAGE | GAP | ACTION | OWNER | DATE | COST\nLearning-science/statistical review | [INPUT] | [INPUT] | advisor/contract [INPUT] | [INPUT] | [INPUT] | $[INPUT]\nPrivacy/security | [INPUT] | [INPUT] | assessment [INPUT] | [INPUT] | [INPUT] | $[INPUT]\nFinance/claims | [INPUT] | [INPUT] | accountant/controller [INPUT] | [INPUT] | [INPUT] | $[INPUT]\nSales/partnerships | [INPUT] | [INPUT] | [INPUT] | [INPUT] | [INPUT] | $[INPUT]." },
      { heading: "Attachments and certification", body: "Attach concise resumes/profiles, role descriptions, organization chart, availability confirmation, relevant project examples, and specialist letters. Each person confirms that the profile is accurate and that committed time is feasible: name/signature/date [INPUT]." },
    ],
  },
  {
    id: "financial-statements", title: "Financial statements", category: "Financial", generated: true, description: "Founder-prepared income statement and balance sheet framework.",
    sections: [
      { heading: "Purpose and basis", body: `Management-prepared financial statements for ${company}. Figures must be updated from the accounting ledger before submission and reviewed for consistency with bank and CRA records.` },
      { heading: "Income statement", body: "Report revenue by product or service, cost of sales, payroll, contractor costs, hosting and software, professional fees, marketing, office and administration, depreciation, interest, taxes, and net income for the current year-to-date and prior fiscal year." },
      { heading: "Balance sheet", body: "Report cash, receivables, prepaid expenses, equipment and intangible assets; accounts payable, payroll and tax liabilities, loans and deferred revenue; share capital, retained earnings, and current-period earnings." },
      { heading: "Management notes", body: "Identify accounting period, reporting currency (CAD), cash or accrual basis, related-party transactions, outstanding tax balances, commitments, contingent liabilities, and material events after period end." },
    ],
  },
  {
    id: "proof-of-funds", title: "Proof of funds summary", category: "Financial", generated: true, description: "Operating-capacity summary to accompany bank evidence.",
    sections: [
      { heading: "Funding capacity", body: `${company} will demonstrate that it can meet payroll and operating obligations while reimbursement claims are processed. Attach recent business bank statements or an official bank letter; redact full account numbers while retaining the account holder, date, and balance.` },
      { heading: "Sources of project cash", body: "List unrestricted cash, forecast operating receipts, founder or shareholder funding formally committed, approved credit facilities, and other confirmed non-IRAP financing. Do not describe uncommitted sales or financing as available funds." },
      { heading: "Coverage test", body: "Compare available liquidity with the maximum cumulative project cash deficit, including eligible costs paid before reimbursement and all non-eligible operating costs. Explain the contingency if receipts or reimbursements are delayed." },
    ],
  },
  {
    id: "projections", title: "Three-year financial projections", category: "Financial", generated: true, description: "Base-case planning assumptions and forecast structure.",
    sections: [
      { heading: "Forecast scope", body: "Prepare monthly forecasts for Year 1 and annual forecasts for Years 2 and 3. Show revenue, gross margin, operating expenses, EBITDA, cash movement, ending cash, headcount, and financing requirements." },
      { heading: "Commercial assumptions", body: "Model design-partner onboarding fees, usage-based API revenue, active tenants, average learning events per tenant, conversion timing, churn, and enterprise-contract timing. Separate Brightwick internal validation from external revenue." },
      { heading: "Cost assumptions", body: "Model Canadian technical payroll, employer costs, cloud hosting, security and compliance, customer onboarding, sales, professional services, and non-cash expenses. State salary and hiring dates by role." },
      { heading: "Scenarios", body: "Include downside, base, and upside cases. Stress-test slower customer acquisition, lower usage, delayed funding, higher cloud cost, and one additional technical hire. Identify the month of lowest cash in each case." },
    ],
  },
  {
    id: "project-budget", title: "Detailed R&D project budget", category: "Financial", generated: true, description: "Cost structure tied to work packages and milestones.",
    sections: [
      { heading: "Budget basis", body: `Budget for ${project}. Use the advisor-confirmed project dates and eligible-cost rules. Record all amounts in CAD and exclude costs incurred outside the approved period.` },
      { heading: "Canadian labour", body: "For each employee list role, work package, annual salary, productive hours, project hours, calculated hourly rate, gross eligible labour, and employer costs only where the contribution agreement permits them." },
      { heading: "Other project costs", body: "Separately list eligible contractors, testing, specialized technical services, materials, and travel only if pre-approved. Identify supplier, purpose, work package, timing, tax treatment, and supporting quotation." },
      { heading: "Funding reconciliation", body: "Show total project cost, eligible cost, requested IRAP contribution, company contribution, other government assistance, and non-eligible cost. Confirm no cost is funded twice." },
    ],
  },
  {
    id: "cash-flow", title: "Project cash-flow forecast", category: "Financial", generated: true, description: "Monthly project liquidity and reimbursement timing.",
    sections: [
      { heading: "Monthly schedule", body: "For every project month show opening cash, operating receipts, financing, payroll, employer remittances, contractors, hosting and other costs, IRAP claims submitted, expected reimbursement receipts, and ending cash." },
      { heading: "Timing assumptions", body: "Use conservative reimbursement timing and place payroll and CRA remittance dates in the month cash leaves the account. Flag the maximum funding gap and minimum cash balance." },
      { heading: "Management response", body: "Document the actions available if cash falls below the operating buffer: defer non-project spend, use committed shareholder funding or approved credit, slow discretionary hiring, or revise project sequencing with IRAP approval." },
    ],
  },
  {
    id: "proposal", title: "Formal R&D project proposal / statement of work", category: "R&D project", generated: true, description: "Objectives, uncertainties, milestones, deliverables, and timeline.",
    sections: [
      { heading: "Project objective", body: `${company} will determine whether a privacy-preserving, content-agnostic adaptive engine can infer reliable learner state from sparse outcomes and select practice that improves durable learning across tenants.` },
      { heading: "Technical uncertainties", body: "The project will test sparse-data mastery estimation, correction of item-difficulty priors from behaviour, durable outcome improvement over a fixed baseline, and safe generalization across different curricula and traffic patterns." },
      { heading: "Systematic work", body: "WP1 compares EWMA, Elo/IRT and confidence-weighted learner models. WP2 develops empirical item calibration and drift controls. WP3 conducts a stable adaptive-versus-baseline outcome experiment. WP4 validates isolation, latency, coverage and mapping with external tenants." },
      { heading: "Milestones and deliverables", body: "M1 model-selection report and versioned parameters (Month 3); M2 calibration pipeline and review thresholds (Month 5); M3 controlled outcome report (Month 8); M4 external-tenant validation and onboarding playbook (Month 10)." },
      { heading: "Success measures", body: "Calibration error, log-loss, cold-start accuracy, prior-versus-observed difficulty error, delayed retention, time-to-mastery, recommendation coverage, p95 latency, tenant-isolation tests, and reproducible model decisions." },
    ],
  },
  {
    id: "technical-docs", title: "Technical engine documentation", category: "R&D project", generated: true, description: "System design, boundaries, model, and integration summary.",
    sections: [
      { heading: "System overview", body: "A standalone TypeScript API receives pseudonymous item outcomes, maintains tenant-scoped learner-skill state, and returns an auditable next-item decision. Customer systems retain identity, content, answer keys, and grading." },
      { heading: "Current baseline", body: "The adaptive-v1 policy uses a difficulty-weighted EWMA mastery estimate, selects the weakest eligible skill, scaffolds repeated errors, and spirals mastered skills. Selection events retain reason, model version, and request context." },
      { heading: "Architecture and controls", body: "Server-to-server bearer-key access, hashed scoped credentials, request validation, rate limiting, composite tenant keys, tenant-filtered queries, idempotent answer events, PostgreSQL persistence, and versioned OpenAPI operations." },
      { heading: "R&D boundary", body: "Routine deployment and API construction establish the experimental platform. The advancement sought is evidence that learner inference and selection remain calibrated, useful, and safe under sparse data and cross-tenant variation." },
    ],
  },
  {
    id: "labour-breakdown", title: "Eligible Canadian R&D labour breakdown", category: "R&D project", generated: true, description: "Role-and-hours planning schedule.",
    sections: [
      { heading: "Required schedule", body: "For each Canadian T4 employee include legal name, role, province, work package, task description, project start and end date, forecast hours by month, gross salary basis, and calculated project labour cost." },
      { heading: "Role allocation", body: "Technical lead: experimental architecture, model implementation, review, and technical decisions. R&D software developer: data pipelines, experiment implementation, tests, and evidence capture. Data or research support, if approved: analysis, calibration, and reporting." },
      { heading: "Cost method", body: "Use payroll-supported salary and the contribution-agreement method for productive hours and eligible employer costs. Reconcile forecasts to contemporaneous timesheets and payroll each claim period; exclude sales, administration, routine maintenance, and unrelated product work." },
    ],
  },
  {
    id: "risk-plan", title: "R&D risk assessment and mitigation plan", category: "R&D project", generated: true, description: "Technical, delivery, evidence, privacy, and commercial risks.",
    sections: [
      { heading: "Technical risks", body: "Sparse data may not support stable estimates; behavioural difficulty may be biased; adaptive selection may show no durable lift; cross-tenant content mappings may be inconsistent. Mitigate with confidence estimates, baselines, pre-defined thresholds, delayed outcomes, and reversible model versions." },
      { heading: "Data and privacy risks", body: "Low event volume, incomplete metadata, accidental identifiers, or tenant leakage could invalidate work. Use metadata-only contracts, opaque learner IDs, schema validation, composite tenant constraints, isolation tests, minimization, retention rules, and incident procedures." },
      { heading: "Delivery and financial risks", body: "Hiring delays, key-person dependency, reimbursement lag, or scope growth may disrupt milestones. Maintain documented experiments, code review, cross-training, monthly cash forecasts, a liquidity buffer, and formal change control." },
      { heading: "Decision gates", body: "At each milestone review evidence, variance, residual risk, and cash. Promote, revise, pause, or roll back the model using documented criteria; seek written IRAP approval before material scope or budget changes." },
    ],
  },
  {
    id: "commercialization", title: "R&D commercialization plan", category: "R&D project", generated: true, description: "How project evidence becomes revenue.",
    sections: [
      { heading: "Commercial outcome", body: "Convert the validated engine into a B2B SaaS decision layer for education applications and tutoring operators that have content and learner traffic but lack an adaptive-learning research team." },
      { heading: "Path to market", body: "Deploy Brightwick in shadow mode; recruit 3-5 design partners; run narrowly scoped pilots; publish credible outcome and integration evidence; standardize onboarding, security review, pricing, and customer success; then expand to schools and professional training." },
      { heading: "Revenue model", body: "Fixed-fee design-partner onboarding, usage-based recommendations and learning events, and annual enterprise contracts for service levels, controls, analytics, experiment tooling, and support." },
      { heading: "Commercial proof points", body: "Days to first recommendation, eligible-bank coverage, retained-learning lift, time-to-mastery, pilot-to-paid conversion, usage growth, gross margin, renewal, p95 latency, and support burden." },
    ],
  },
  { id: "timesheets", title: "R&D activity timesheets", category: "Reimbursement substantiation", description: "Contemporaneous hours tied to approved work packages." },
  { id: "claim-payroll", title: "Payroll evidence for claimed labour", category: "Reimbursement substantiation", description: "Payroll register, pay evidence, and remittance support." },
  { id: "invoices", title: "Eligible cost invoices and receipts", category: "Reimbursement substantiation", description: "Supplier evidence for approved non-labour costs." },
  { id: "progress", title: "Milestone progress reports", category: "Reimbursement substantiation", description: "Progress and variances against the contribution agreement." },
  {
    id: "business-plan", title: "Current business plan", category: "Business context", generated: true, description: "Company, product, market, operations, and growth plan.",
    sections: [
      { heading: "Executive summary", body: `${company} is productizing a Canadian adaptive-learning decision engine. The API helps learning platforms choose the next practice item while customers retain learner identity, content, and grading. Brightwick is the first integration and evidence environment.` },
      { heading: "Problem and solution", body: "Most practice products deliver fixed sequences. Credible adaptivity requires learner modelling, calibration, experimentation, privacy engineering, and outcome data. Opyjo offers these capabilities as an auditable server-to-server API." },
      { heading: "Customers and business model", body: "Initial customers are EdTech applications and tutoring operators, followed by schools and professional training. Revenue combines onboarding, usage-based API charges, and enterprise annual contracts." },
      { heading: "Operations and team", body: "The company will maintain Canadian R&D capability, secure cloud operations, disciplined experiment records, customer onboarding, and financial controls. Hiring and external specialists will follow validated technical and commercial needs." },
      { heading: "Objectives", body: "Complete the 10-month R&D programme; validate durable learning outcomes; onboard 3-5 design partners; convert successful pilots to paid usage; and establish repeatable onboarding, evidence, security, and support practices." },
    ],
  },
  {
    id: "market-analysis", title: "Market and competitive analysis", category: "Business context", generated: true, description: "Segments, alternatives, differentiation, and validation plan.",
    sections: [
      { heading: "Target segments", body: "Prioritize Canadian and North American EdTech applications and tutoring operators with existing digital content, sufficient learner events, an identified personalization problem, and no internal psychometrics or adaptive-platform team." },
      { heading: "Customer alternatives", body: "Fixed sequencing and hand-authored rules; building an internal model and experimentation stack; broad learning-management platforms; assessment and analytics vendors; or delaying personalization. Validate named competitors and current pricing before external submission." },
      { heading: "Differentiation", body: "Metadata-only integration, customer custody of content and identity, auditable decisions, tenant isolation, versioned models, measurable learning outcomes, and a narrow API that complements rather than replaces the customer product." },
      { heading: "Validation programme", body: "Conduct 5-10 structured discovery interviews, secure 3-5 design partners, document current workflow and willingness to pay, measure integration time and outcome value, and record loss reasons. Update market sizing from cited current sources." },
    ],
  },
  {
    id: "product-roadmap", title: "Product and commercialization roadmap", category: "Business context", generated: true, description: "Phased technical and market execution plan.",
    sections: [
      { heading: "Phase 1 - Foundation", body: "Provision managed staging, deploy the service, synchronize Brightwick metadata, validate monitoring and backups, and begin shadow-mode comparison. Exit when decisions are reliable, auditable, and operationally safe." },
      { heading: "Phase 2 - R&D evidence", body: "Complete sparse-data model comparison and empirical difficulty calibration. Exit with versioned model decisions, calibrated thresholds, reproducible analysis, and documented limitations." },
      { heading: "Phase 3 - Outcome validation", body: "Run adaptive-versus-baseline testing with delayed review outcomes and guardrails. Exit with a defensible promote, revise, or rollback decision." },
      { heading: "Phase 4 - Design partners", body: "Onboard 3-5 external tenants, validate mapping, isolation, latency, coverage, and support needs, and convert successful pilots into paid usage." },
      { heading: "Phase 5 - Scale", body: "Standardize self-serve onboarding, security materials, service levels, analytics, pricing, and customer success; expand into schools and professional training when privacy and outcome evidence support the move." },
    ],
  },
];

const verifiedTechnology = `VERIFIED FROM REPOSITORY (July 12, 2026)\nProduct: standalone, content-agnostic, multi-tenant adaptive-learning API.\nRuntime: Node.js 24, TypeScript 5.9, Fastify 5, PostgreSQL 17 locally; Docker image and Railway deployment configuration are present.\nValidation: 16 automated tests pass; 3 database integration tests are defined but skipped without TEST_DATABASE_URL. TypeScript build and ESLint pass.\nCurrent status: code-complete and locally validated. Production deployment, managed-database migration execution, restore/load/privacy testing, Brightwick shadow integration, and learning-outcome validation must not be represented as complete until evidence exists.`;

const requiredInputs = `SUBMISSION INPUTS STILL REQUIRED\n[INPUT] Legal corporation name, incorporation jurisdiction/date, CRA business number, registered address, fiscal year-end, and ownership percentages.\n[INPUT] Project start/end dates and the ITA-approved scope.\n[INPUT] Named project personnel, Canadian work location, employment status, salary, productive-hours method, and monthly project hours.\n[INPUT] Actual historical financial statements, bank balances, financing commitments, tax balances, and monthly forecast assumptions.\n[INPUT] Current customers/revenue, interview evidence, pipeline, pricing validation, market-source citations, and signed partner evidence.\n[INPUT] Requested contribution, confirmed eligible-cost treatment, claim frequency, and other government assistance.\nThese fields must be completed from source records. The application must not substitute estimates for verified facts without labelling them as assumptions.`;

const supplementalSections: Record<string, Array<{ heading: string; body: string }>> = {
  "financial-statements": [
    { heading: "Statement presentation", body: `Present comparative figures for the last completed fiscal year and current year-to-date. Include an income statement, balance sheet, and cash-flow reconciliation in CAD. Each statement must show period dates and whether figures are unaudited, notice-to-reader, reviewed, or audited.\n\nINCOME STATEMENT LINES\nRevenue - Brightwick / consumer products | Revenue - adaptive-engine customers | Other revenue | Cost of sales | Gross profit | Canadian salaries and wages | Employer payroll costs | Contractors | Cloud and software | R&D tools | Sales and marketing | Professional fees | Insurance | Office and administration | Depreciation | Interest | Income tax | Net income.\n\nBALANCE SHEET LINES\nCash | Accounts receivable | Sales taxes recoverable | Prepaids | Equipment | Capitalized development, if applicable | Accounts payable | Payroll/CRA liabilities | Deferred revenue | Loans/shareholder advances | Share capital | Retained earnings.` },
    { heading: "Reconciliation and supporting file", body: "Attach the general ledger or trial balance, business bank reconciliation, aged receivables/payables, CRA account balances, and explanations for material year-over-year movements. The cash balance must reconcile to the proof-of-funds document. Payroll expense must reconcile to the labour budget and payroll source records. Identify any related-party costs and the basis on which they were recorded." },
    { heading: "Management representation", body: `Management should sign and date a statement confirming that the information is complete, prepared from company records, and discloses all material liabilities, commitments, related-party transactions, government assistance, and events after period end.\n\n${requiredInputs}` },
  ],
  "proof-of-funds": [
    { heading: "Liquidity certificate", body: "As at [INPUT DATE], unrestricted business cash is $[INPUT], committed undrawn credit is $[INPUT], and documented shareholder funding available to the project is $[INPUT]. Restricted funds and unconfirmed sales are excluded. Attach bank evidence dated within 30 days and signed commitment documents for any shareholder or lender support." },
    { heading: "Project coverage calculation", body: "Available liquidity $[INPUT] less minimum operating reserve $[INPUT] equals project-available liquidity $[INPUT]. Maximum cumulative project cash deficit before IRAP reimbursement is $[INPUT]. Coverage ratio is [INPUT]x. The forecast must assume reimbursement only after a complete, correct claim and should tolerate at least the published NRC service-standard window without missing payroll or CRA remittances." },
    { heading: "Contingency and authorization", body: "Trigger: projected cash falls below $[INPUT] or [INPUT] months of fixed costs. Owner: [INPUT]. Actions in order: freeze discretionary non-project spend; collect receivables; draw only committed facilities; use documented shareholder funding; rephase work with written IRAP approval. Management approval: [NAME / TITLE / DATE]." },
  ],
  "projections": [
    { heading: "Three-year operating model", body: "Build monthly columns for the first 12 months and annual totals for Years 2 and 3. Driver rows must include: design partners signed, paid pilots, production tenants, active learners, recommendations/events per learner, onboarding fee, price per usage unit, enterprise recurring revenue, churn, gross margin, collection period, technical headcount, hiring dates, salary inflation, hosting per million events, sales cost, security/compliance spend, and capital requirements." },
    { heading: "Required outputs", body: "For downside, base, and upside cases show revenue, gross profit, EBITDA, net income, operating cash flow, financing, ending cash, monthly burn, runway, headcount, Canadian R&D payroll, break-even month, and lowest cash point. Include formulas and an assumptions tab so every output is traceable. Do not count Brightwick internal usage as external revenue." },
    { heading: "Scenario logic and management gates", body: "Downside: partner recruitment and paid conversion delayed by [INPUT] months, usage [INPUT]% below base, no uncommitted financing. Base: signed or evidence-supported assumptions only. Upside: higher conversion/usage but no unexplained margin improvement. Gate hiring and discretionary spend to cash runway, signed revenue, and completion of technical milestones." },
    { heading: "Model completion record", body: requiredInputs },
  ],
  "project-budget": [
    { heading: "Work-package cost schedule", body: "Create one row per person and cost category, split by month and WP1-WP4. Required columns: resource; Canadian work location; employee/contractor; task; work package; start/end; annual salary or supplier rate; productive hours; project hours; hourly cost calculation; gross cost; eligible percentage; eligible amount; IRAP contribution; company contribution; other assistance; evidence source." },
    { heading: "Budget control rules", body: "Include only necessary project costs within the approved period and contribution agreement. Exclude day-to-day operations, non-technical commercial work, work outside Canada, and any unsupported or double-funded cost. Do not assume overhead, employer costs, contractors, travel, cloud, or taxes are eligible: mark each as pending ITA confirmation until written cost rules are available." },
    { heading: "Milestone reconciliation", body: "WP1 sparse-data learner model - $[INPUT], [INPUT] hours. WP2 empirical difficulty calibration - $[INPUT], [INPUT] hours. WP3 adaptive outcome experiment - $[INPUT], [INPUT] hours. WP4 external-tenant validation - $[INPUT], [INPUT] hours. Project management and evidence reporting - $[INPUT], only to the extent approved. Total project $[INPUT]; requested IRAP $[INPUT]; company cash contribution $[INPUT]." },
    { heading: "Approvals and version control", body: "Budget owner: [INPUT]. Technical approver: [INPUT]. Version/date: [INPUT]. Document assumptions, quotations, salary source records, and every approved budget transfer. No material scope or category change is effective until written approval is retained." },
  ],
  "cash-flow": [
    { heading: "Monthly cash schedule", body: "For each project month include opening unrestricted cash; customer collections; confirmed financing; payroll payment; payroll remittance; contractor payment; cloud/testing costs; other operating costs; claim-period eligible cost; claim submission date; assumed reimbursement date; reimbursement received; sales-tax movement; closing cash; and minimum-reserve variance." },
    { heading: "Claim timing model", body: "Model claims after costs are incurred and paid unless the agreement states otherwise. Separate claimed amount from expected contribution. Include a delay case using the NRC published service standard of up to 35 business days after receipt of all required documents and a correctly completed claim; this is a planning assumption, not a payment guarantee." },
    { heading: "Cash-risk dashboard", body: "Report maximum pre-reimbursement exposure $[INPUT], lowest monthly cash $[INPUT], reserve threshold $[INPUT], months of runway [INPUT], and owner action date [INPUT]. Reconcile monthly salary cash to the labour schedule and reimbursement to the budget. Explain any negative cash month and identify committed—not hoped-for—funding used to cure it." },
  ],
  "proposal": [
    { heading: "Starting point and advancement sought", body: `${verifiedTechnology}\n\nThe baseline adaptive-v1 model is a difficulty-weighted EWMA beginning at 0.5 with learning rate 0.15. It scaffolds after two consecutive wrong answers, targets the weakest skill below 0.8, otherwise spirals the least recently practised skill, maps mastery to difficulty bands, and avoids the last 30 items or 14 days where possible. This is an engineered hypothesis—not yet evidence of accurate learner inference or durable learning gains.\n\nAdvancement sought: a confidence-aware, empirically calibrated, privacy-preserving learner-and-item decision system that remains reliable with sparse data and heterogeneous tenant curricula, supported by reproducible outcome evidence.` },
    { heading: "WP1 - Sparse-data learner model", body: "Question: can learner state be estimated reliably before enough responses exist for conventional calibration? Compare adaptive-v1 EWMA against Elo/IRT-inspired and confidence-weighted alternatives using replay simulation and, when available, prospective data. Define train/validation separation, cold-start cohorts, missing-data handling, versioned parameters, and rollback. Acceptance evidence: log-loss/Brier score, calibration error, ranking stability, uncertainty coverage, and observations-to-stability by cohort. Deliverable: model-selection report, code, parameter registry, limitations, and decision." },
    { heading: "WP2 - Empirical item difficulty", body: "Question: can tenant-supplied 1-5 difficulty priors be corrected without overreacting to biased or low-volume behaviour? Estimate performance conditional on learner state; define minimum samples, confidence intervals, shrinkage, drift monitoring, tenant/global pooling rules, and human-review thresholds. Acceptance evidence: prior-versus-observed error, held-out predictive improvement, recalibration stability, drift false-positive rate, and documented failure cases. Deliverable: versioned calibration pipeline and audit report." },
    { heading: "WP3 - Durable outcome experiment", body: "Question: does adaptive-v1 or its successor improve retained learning rather than only immediate correctness or engagement? Use stable learner assignment and an agreed baseline; pre-register primary outcome, delayed-review window, exclusions, sample-size rationale, stopping rules, guardrails, and analysis. Primary candidates: delayed retention and time-to-mastery. Guardrails: completion, error streak, fallback rate, latency, support incidents, and subgroup harm. Deliverable: reproducible analysis and promote/revise/rollback decision." },
    { heading: "WP4 - Cross-tenant validation", body: "Question: does the content-agnostic model remain useful and safe across different skill taxonomies, banks, volumes, and integration patterns? Onboard 3-5 design partners using metadata-only contracts and opaque IDs. Test mapping quality, recommendation coverage, tenant isolation, retry/idempotency, latency, outage fallback, deletion/export procedures, and integration time. Deliverable: partner evidence, hardened onboarding playbook, limitations, and commercial-readiness decision." },
    { heading: "Milestones, governance, and Canadian benefit", body: "M1 Month 1: experimental protocol and baseline evidence pack. M2 Month 3: WP1 decision. M3 Month 5: WP2 calibrated pipeline. M4 Month 8: WP3 outcome report. M5 Month 10: WP4 validation and commercialization gate. Monthly technical reviews retain hypotheses, commits, datasets, results, failures, timesheets, and decisions. Expected Canadian benefit must be completed with verified numbers: [INPUT] Canadian R&D jobs retained/created, [INPUT] revenue/export potential, Canadian-owned IP position, and new in-house modelling/security capability." },
    { heading: "Submission completion", body: requiredInputs },
  ],
  "technical-docs": [
    { heading: "Verified component inventory", body: `${verifiedTechnology}\n\nCore: dependency-free mastery and selection policy. HTTP: Fastify, Zod validation, shaped errors, Helmet headers, 1 MB body limit, request IDs, and configurable rate limiting (default documented as 600 requests/minute). Persistence: pg repository and six tenant-keyed tables. Security: one-time-issued bearer keys, stored hashes, scopes, expiry/revocation, constant-time comparison, server-to-server boundary. Delivery: multi-stage non-root Docker image; Railway readiness probe and restart policy.` },
    { heading: "Data model and auditability", body: "tenants; api_keys; items (metadata only); learner_skill_state; append-only answer_events; append-only selection_events. Answer events retain mastery before/after, attempts, consecutive errors, algorithm version, occurred/received time, and idempotency key. Selection events retain item, skill, reason, mastery before, candidate count, algorithm version, request filters, and selected time. Composite tenant references and tenant-leading indexes enforce structural isolation; RLS is enabled with no policies for non-owner access paths." },
    { heading: "API and failure behaviour", body: "Operations: item upsert, bulk upsert up to 1,000 atomically, item deactivation, answer event, next-item, learner mastery, tenant skill summary, liveness, and database readiness. Retries with the same answer idempotency key return the original result; reuse with different content returns conflict. If no ideal selection exists, the explicit relaxation ladder returns fallback. Tenant clients must use a local fallback on timeout/5xx and back off on 429." },
    { heading: "Verification matrix", body: "Verified: 16 unit/HTTP/security tests pass; build and lint pass. Defined but not executed in this review: 3 PostgreSQL integration tests requiring TEST_DATABASE_URL. Required before production evidence: managed migration result, database integration suite, cross-tenant negative tests, RLS/non-owner access test, load/soak results, latency/error metrics, backup and restore drill, key rotation, privacy/threat model, penetration test, data retention/export/deletion, incident response, and Brightwick shadow comparison." },
    { heading: "Known limitations", body: "The EWMA mastery value is not yet empirically calibrated as a probability of mastery. Item difficulty is tenant/default input; empirical source exists in schema but no calibration job is implemented. No evidence yet demonstrates causal learning improvement, fairness, generalization, production availability, or external partner adoption. These limitations define the proposed R&D rather than weaken it when disclosed accurately." },
  ],
  "labour-breakdown": [
    { heading: "Detailed labour schedule template", body: "EMPLOYEE | ROLE | PROVINCE | T4 STATUS | WP | TECHNICAL TASK | MONTH | PROJECT HOURS | TOTAL PAID HOURS | SALARY SOURCE | HOURLY METHOD | ELIGIBLE COST | TIMESHEET LINK\n[INPUT] | Technical lead | [INPUT] | [INPUT] | WP1/WP2/WP3 | model design, implementation, review | M1-M10 | [INPUT] | [INPUT] | payroll | [ITA-confirmed] | $[INPUT] | [INPUT]\nOluwamayomikun [confirm legal name] | R&D software developer [confirm] | Ontario | [INPUT] | [INPUT] | experiment/data/test tasks only | [INPUT] | [INPUT] | [INPUT] | payroll | [ITA-confirmed] | $[INPUT] | [INPUT]" },
    { heading: "Task eligibility boundary", body: "Include documented experimental design, algorithm alternatives, data/analysis pipelines, technical testing, calibration, experiment infrastructure, evidence interpretation, and approved technical partner integration. Segregate routine deployment, ordinary maintenance, customer support, marketing, sales, finance, corporate filings, and unrelated Brightwick work. Where a task supports both, record a defensible allocation and explanation." },
    { heading: "Monthly reconciliation", body: "Employee and manager sign contemporaneous time by date, WP, activity, result, and hours. Monthly controller review reconciles timesheets to payroll register, bank payment, CRA remittance, budget, claim amount, leave, and other government assistance. Retain variance explanations and prevent one hour from being charged to two programs." },
    { heading: "Completion fields", body: requiredInputs },
  ],
  "risk-plan": [
    { heading: "Risk register - technical", body: "T1 Sparse data produces unstable rankings (High/High): confidence intervals, shrinkage, baseline comparison; owner [INPUT]; trigger calibration error >[INPUT]. T2 behavioural item estimates are confounded (High/Med): conditional models, minimum samples, tenant stratification. T3 no durable lift (High/Med): pre-registered controlled test and rollback. T4 cold-start harms learners (High/Med): conservative policy, scaffold guardrails, monitoring. T5 cross-tenant mapping fails (Med/High): mapping validation and coverage threshold." },
    { heading: "Risk register - security and operations", body: "S1 tenant leakage (Critical/Low target): tenant-scoped SQL, composite keys, RLS, negative isolation tests. S2 accidental PII transfer (High/Med): opaque-ID contract, schema validation, tenant review, logs scan. S3 key exposure (High/Med): server-only scoped keys, hash storage, rotation/revocation. O1 database loss (High/Low target): backups, point-in-time recovery, restore drill. O2 service outage (Med/Med): readiness probes, alerts, tenant fallback, retry idempotency. Evidence owner and due date required for every control." },
    { heading: "Risk register - project and commercial", body: "P1 integration-test environment unavailable; P2 insufficient event volume; P3 hiring/key-person delay; P4 reimbursement timing stresses cash; P5 scope drifts into routine engineering; C1 partners do not convert; C2 sales cycle longer than runway. Record likelihood, impact, score, preventive action, contingency, owner, due date, residual rating, trigger, and status monthly." },
    { heading: "Stage-gate authority", body: "Technical lead recommends promote/revise/rollback. Project owner approves continued spend against evidence and liquidity. Privacy/security owner accepts residual operational risk. Finance verifies cost and claim support. Material scope, milestone, resource, or budget changes require documented IRAP approval before implementation." },
  ],
  "commercialization": [
    { heading: "Beachhead and buyer", body: "Beachhead: EdTech applications and tutoring operators that own digital content and learner traffic but lack an adaptive-learning research/platform team. Economic buyer: founder, product/technology leader, or learning leader. User: tenant engineering/product team. Trigger: personalization roadmap, poor fixed sequencing, need for outcome evidence, or inability to hire specialist capability. Exclude organizations without structured item metadata, integration capacity, or sufficient event volume until onboarding is simplified." },
    { heading: "Offer and pricing hypotheses", body: "Design-partner package: metadata mapping, sandbox tenant, shadow integration, experiment plan, and support for $[INPUT]. Growth: usage charge based on [recommendations/events/active learners] at $[INPUT], with minimum $[INPUT]. Enterprise: annual commitment $[INPUT] for SLA, data controls, analytics, experiments, and support. All pricing remains hypothesis until supported by dated interviews, proposals, or contracts." },
    { heading: "Commercial funnel and evidence", body: "Months 1-2: Brightwick shadow evidence. Months 2-5: [INPUT] discovery interviews and 3-5 signed design-partner LOIs. Months 4-8: pilots with integration and outcome baselines. Months 7-10: paid-conversion proposals. KPIs: qualified pipeline, partner commitment, days to first recommendation, bank coverage, event volume, retained-learning evidence, pilot-to-paid conversion, annual contract value, gross margin, renewal intent, and Canadian/export revenue." },
    { heading: "Competitive advantage and IP", body: "Defensibility is expected to compound through privacy-preserving longitudinal outcome evidence, calibrated parameters, reproducible experiments, integration tooling, auditability, and trust. Source code alone is not the moat. Complete an IP inventory, contributor-assignment review, trademark plan, freedom-to-operate/landscape assessment as appropriate, open-source dependency record, and data-rights terms for aggregate learning and model improvement." },
    { heading: "Canadian benefit and completion", body: `Quantify [INPUT] Canadian technical jobs, [INPUT] retained jobs, $[INPUT] Canadian payroll, $[INPUT] three-year revenue, $[INPUT] export revenue, and Canadian-controlled IP/capability. Explain spillovers to Canadian education technology and supplier partners.\n\n${requiredInputs}` },
  ],
  "business-plan": [
    { heading: "Company and eligibility profile", body: `${company} is intended to develop and commercialize technology from Canada. Complete: incorporation jurisdiction/date [INPUT], CRA BN [INPUT], registered/operating address [INPUT], FTE count [INPUT], ownership and control [INPUT], fiscal year-end [INPUT], management profiles [INPUT], current products/revenue [INPUT], and confirmation that the corporation is for-profit and not an excluded entity type. Attach source documents rather than relying on this narrative.` },
    { heading: "Product and verified current capability", body: `${verifiedTechnology}\n\nThe customer retains learner identity, content, answer keys, rendering, and grading. The engine receives an opaque learner ID, item metadata, and correct/incorrect outcomes; it maintains tenant-scoped skill state and returns an auditable item ID and reason. Brightwick is the first intended tenant and rollout evidence source, but the core contains no Brightwick, Ontario, school-grade, or Supabase assumption.` },
    { heading: "Strategy and objectives", body: "Near term: production-ready experimental platform and Brightwick shadow evidence. R&D: resolve sparse inference, difficulty calibration, durable learning, and cross-tenant generalization. Commercial: 3-5 design partners, paid conversion, repeatable onboarding, and validated pricing. Capability: Canadian technical employment, experiment governance, security/privacy controls, and financial reporting. Each objective requires baseline, target, owner, date, budget, and evidence link." },
    { heading: "Organization and execution", body: "Provide an organization chart and profiles for the senior executive, technical lead, R&D developer(s), finance/claim owner, commercialization owner, and external specialists. For each, state relevant accomplishments, committed time, location, employment status, project responsibility, decision authority, and succession/coverage. Identify capability gaps and dated hiring or advisory actions." },
    { heading: "Financial and funding plan", body: "Summarize last fiscal year and YTD revenue, gross profit, net income, cash, liabilities, monthly burn, runway, taxes current/arrears, financing, and contingent obligations. Reconcile to attached financial statements. Explain how the company funds the reimbursable gap and commercialization after the project. Disclose all requested/received government assistance and stacking treatment." },
    { heading: "Management dashboard and appendices", body: `Monthly board/management dashboard: technical milestone status, experimental evidence, budget variance, cash/runway, hiring, partner funnel, production risk, and Canadian-benefit KPIs. Append incorporation/ownership, management profiles, financial statements, proof of funds, projections, project proposal/budget, market analysis, roadmap, risk register, IP inventory, partner evidence, and source bibliography.\n\n${requiredInputs}` },
  ],
  "market-analysis": [
    { heading: "Market definition and segmentation", body: "Define the market narrowly as adaptive decision infrastructure for digital learning providers—not the entire global education market. Segment by customer type, geography, learner volume, content-bank maturity, integration capability, privacy burden, buying trigger, buyer, sales cycle, willingness to pay, and obtainable accounts. Calculate TAM/SAM/SOM bottom-up: number of qualifying accounts x evidence-supported annual contract value. Cite current, dated sources and show formulas." },
    { heading: "Competitor and alternative matrix", body: "Evaluate at least: internal fixed sequencing/rules; internal custom build; LMS/platform-native adaptivity; assessment/psychometric vendors; adaptive-learning API or platform vendors; and doing nothing. Columns: target buyer, content custody, identity/PII boundary, learner model, item calibration, experiment evidence, auditability, integration time, tenant isolation, pricing, strengths, gaps, and source/date. Do not make superiority claims without cited evidence or direct testing." },
    { heading: "Primary research protocol", body: "Interview 5-10 qualified buyers before final submission if possible. Record role/company/segment/date (with consent), current workflow, cost of problem, data volume, decision process, security requirements, alternatives considered, budget, purchasing timeline, pilot conditions, willingness to pay, objections, and next commitment. Distinguish compliments from evidence: LOI, data access, technical workshop, pilot agreement, or payment." },
    { heading: "Positioning and testable hypotheses", body: "Positioning hypothesis: a privacy-minimized, content-agnostic, auditable adaptive API lets learning companies add evidence-led personalization without building a research platform or surrendering content and identity. Test: integration under [INPUT] days; eligible-bank coverage >[INPUT]%; p95 response <[INPUT] ms; measurable delayed-retention or time-to-mastery improvement; pilot-to-paid conversion [INPUT]%. Record results and revise the segment or offer when thresholds fail." },
    { heading: "Evidence still required", body: requiredInputs },
  ],
  "product-roadmap": [
    { heading: "Current baseline - verified", body: `${verifiedTechnology}\n\nRepository includes OpenAPI 3.1, plain-SQL migrations, tenant creation/migration scripts, environment validation, Docker Compose, a non-root production image, Railway health configuration, Supabase CA certificate path, and Brightwick integration guidance. No production deployment or live learner-outcome claim is inferred from configuration files alone.` },
    { heading: "Phase 0 - Production experimental platform", body: "Exit evidence: managed Canadian/approved-region PostgreSQL provisioned; migrations applied; database integration tests pass; secrets and scoped environment keys; HTTPS; logs/metrics/alerts; backup and restore drill; privacy/threat review; load baseline; key rotation; retention/export/deletion; incident runbook. Owner [INPUT], date [INPUT], budget [INPUT]." },
    { heading: "Phase 1 - Brightwick shadow validation", body: "Bulk-sync metadata; generate stable opaque learner IDs; shadow next-item decisions without changing experience; dual-write outcomes using answer UUID as idempotency key; compare old/new decisions, mastery trajectories, fallback rate, latency, retry behaviour, and errors; verify immediate rollback. Exit threshold and feature-flag ramp require [INPUT]." },
    { heading: "Phase 2 - WP1/WP2 model evidence", body: "Months 1-5: dataset specification and governance; baseline replay; candidate model comparison; uncertainty estimates; item calibration; drift controls; version registry; reproducible reports; review gate. No model promotion without pre-defined metrics, limitation analysis, and rollback package." },
    { heading: "Phase 3 - WP3 outcome validation", body: "Months 4-8: pre-register experiment; stable assignment; baseline and adaptive cohorts; delayed outcomes; guardrails; sample-size rationale; monitored run; locked analysis; technical interpretation. Exit: promote/revise/rollback decision, not a requirement to report a positive effect." },
    { heading: "Phase 4 - WP4 design partners and commercialization", body: "Months 6-10: recruit and contract 3-5 partners; validate skill mapping, isolation, coverage, latency, reliability, privacy, and support effort; complete pricing tests and conversion proposals. Exit: onboarding playbook, partner evidence, production control gaps, unit economics, and go/no-go segment decision." },
    { heading: "Post-project scale", body: "Standardize tenant control plane, self-serve onboarding, service levels, usage metering/billing, experiment dashboards, security package, customer success, and model monitoring. Gate school-board expansion on privacy, procurement, accessibility, security, and outcome evidence. Maintain roadmap dependencies, owner, target date, cost, success metric, evidence, and status in a monthly register." },
  ],
};

export const irapDocuments: IrapDocument[] = baseDocuments.map((document) => ({
  ...document,
  sections: document.sections
    ? [...document.sections, ...(supplementalSections[document.id] ?? [])]
    : undefined,
}));

export const documentCategories: DocumentCategory[] = ["Corporate & legal standing", "Employment & payroll", "Financial", "R&D project", "Reimbursement substantiation", "Business context"];
