"use client";

import { useState } from "react";

type Phase = { number:number; group:string; title:string; summary:string; checks:string[]; caution?:string };
const phases:Phase[]=[
  {number:1,group:"Discover",title:"Qualify the client",summary:"Record the organization, contacts, learners, applications, curriculum, volume, launch, hosting, retention, incident and research needs before issuing credentials.",checks:["Technical and privacy contacts confirmed","Learner age range and market documented","Test and production URLs recorded","Pilot size, volume and launch date understood"],caution:"Do not promise legal compliance, learning outcomes, calibration, or unvalidated features."},
  {number:2,group:"Discover",title:"Confirm technical readiness",summary:"Make sure the client has the foundations required for a safe server-to-server integration.",checks:["HTTPS-capable backend and secret manager","Stable item and opaque learner IDs","Server-side grading and persistent attempt IDs","Safe test environment"]},
  {number:3,group:"Prepare",title:"Prepare the engine environment",summary:"Verify build quality, migrations, health endpoints, Canadian residency, recovery, alerts, capacity and the documented algorithm version.",checks:["Build, lint, unit and integration tests pass","/health/live and /health/ready return 200","Test and production databases are separate","Backups, recovery and monitoring are enabled"],caution:"Never give a client localhost or an unstable preview URL."},
  {number:4,group:"Provision",title:"Create isolated tenants",summary:"Create a test tenant first and a separate production tenant only after test acceptance. Record ownership and policy metadata without recording secrets.",checks:["Unique test tenant created","Production tenant deferred until acceptance","Tenant UUID, slug, scopes and owner recorded","Retention and research settings recorded"]},
  {number:5,group:"Provision",title:"Issue least-privilege API keys",summary:"Deliver one-time keys through an approved secret-sharing mechanism with only the scopes each component needs.",checks:["Separate test and production keys","Recipient and issue date recorded—not secret","Rotation and emergency revocation agreed","No key sent by ordinary email or chat"]},
  {number:6,group:"Provision",title:"Configure tenant settings",summary:"Confirm strategy, retention preference and research participation. Use balanced strategy and research opt-out as the safe defaults.",checks:["Strategy documented","Research participation false by default","Retention preference recorded","Current enforcement limitations disclosed"]},
  {number:7,group:"Content",title:"Select or import curricula",summary:"Choose official shared curricula, publisher extensions, or both. Validate source rights, bilingual labels, identifiers, hierarchy and prerequisite direction.",checks:["Source and usage permission confirmed","Jurisdiction, subject and version validated","Cycle detection tested","Client reviewed the test graph"],caution:"Never invent expectations or silently scrape a government or publisher source."},
  {number:8,group:"Content",title:"Define the metadata contract",summary:"Agree on permanent IDs, skills, grades, difficulty, tags, concept mappings, primary concepts, synchronization and retirement rules.",checks:["One reviewed example supplied","Small fixture tested before full upload","Edit and retirement rules documented","Question content and answer keys excluded"]},
  {number:9,group:"Content",title:"Validate the catalogue",summary:"Check item counts, identity stability, difficulty, grades, active status, coverage, mappings and sufficient banks for each quiz mode.",checks:["No duplicates or unstable IDs","Valid grades and difficulty values","Concept mappings are accessible","No unexpected bank_exhausted response"]},
  {number:10,group:"Validate",title:"Test the complete learner loop",summary:"With synthetic learners, test recommendation, client lookup, grading, reporting, mastery, replay protection, updated selection and persistent progress.",checks:["Diagnostic, practice, remediation and review tested","Evidence updates exactly once","Replay returns replayed: true","Conflicting idempotency reuse is rejected"]},
  {number:11,group:"Validate",title:"Test isolation and security",summary:"Prove tenant, environment and scope isolation; inspect bundles and logs for secret leakage; verify rate limits, Supabase roles and RLS.",checks:["Cross-tenant access fails","Test key cannot reach production","Malformed and revoked credentials fail","Bearer tokens absent from browser and logs"]},
  {number:12,group:"Validate",title:"Test failure and recovery",summary:"Exercise timeouts, 5xx, invalid keys, rate limits, empty banks, missing content, duplicates, database failure and rollback.",checks:["Client fallback keeps the app usable","Answer retries reuse the same key","Empty banks have a safe response","Previous selection logic can be restored"]},
  {number:13,group:"Pilot",title:"Run shadow mode",summary:"Keep existing learner-facing selection while comparing engine recommendations in parallel before enabling a small approved pilot cohort.",checks:["Existing choice remains learner-facing","Both decisions captured safely","Latency and eligibility compared","Mismatches investigated before pilot"],caution:"Different recommendations alone do not prove improved learning outcomes."},
  {number:14,group:"Govern",title:"Complete privacy and operational sign-off",summary:"Assign ownership for legal authority, agreements, assessments, residency, deletion, incidents, backups, accessibility and human override.",checks:["Privacy and processing responsibilities signed","PIA and algorithmic assessment reviewed","Residency and subprocessors disclosed","Incident and deletion procedures assigned"]},
  {number:15,group:"Launch",title:"Launch production",summary:"Approve a written production checklist, start with a limited pilot and expand only after reviewing reliability, quality and support evidence.",checks:["Production tenant and catalogue ready","Monitoring and named responders active","Fallback and rollback documented","Support contacts and escalation hours agreed"]},
  {number:16,group:"Operate",title:"Monitor after launch",summary:"Watch endpoint volume and latency, auth failures, bank exhaustion, errors, exposure, fallbacks, retries, drift and unexpected state resets.",checks:["Operational dashboard active","Catalogue drift monitored","Cohort suppression checked","Support access has an approved purpose"]},
  {number:17,group:"Operate",title:"Deliver the handover package",summary:"Provide URLs, securely shared credentials, scopes, OpenAPI, onboarding guide, conventions, curricula, examples, support, limitations and acceptance criteria.",checks:["OpenAPI and examples supplied","Rotation and incident process supplied","Known limitations stated","Actual keys excluded from ordinary documents"]},
  {number:18,group:"Close",title:"Offboard or suspend safely",summary:"Confirm authority, revoke keys, suspend access, follow export and retention agreements, account for backups, preserve required audit evidence and update records.",checks:["All credentials revoked","Export/deletion authority verified","Backups and legal holds addressed","Completion confirmed with authorized contact"],caution:"Do not promise automated export or deletion while those endpoints are not implemented."},
];
const groups=["All",...Array.from(new Set(phases.map(p=>p.group)))];

function CopyCode({children}:{children:string}) { const [copied,setCopied]=useState(false);return <div className="runbook-code"><button onClick={async()=>{await navigator.clipboard.writeText(children);setCopied(true);setTimeout(()=>setCopied(false),1500)}}>{copied?"Copied":"Copy"}</button><pre><code>{children}</code></pre></div> }

export function OwnerRunbook(){
  const [group,setGroup]=useState("All"); const [completed,setCompleted]=useState<number[]>([]); const shown=phases.filter(p=>group==="All"||p.group===group); const toggle=(n:number)=>setCompleted(c=>c.includes(n)?c.filter(x=>x!==n):[...c,n]);
  return <>
    <header className="section-header"><div className="eyebrow"><span/>Operator playbook</div><h1>Adaptive Engine owner runbook.</h1><p>The internal process for giving each client a secure, isolated and tested connection—then supporting them until the full recommendation and answer-reporting loop works safely.</p></header>
    <section className="runbook-summary"><div><span>Onboarding phases</span><strong>18</strong><small>qualification through offboarding</small></div><div><span>Completed here</span><strong>{completed.length}</strong><small>interactive working checklist</small></div><div><span>Safe default</span><strong>Opt out</strong><small>cross-tenant research</small></div><div><span>Launch model</span><strong>Pilot</strong><small>limited traffic first</small></div></section>
    <section className="runbook-principle"><i>◎</i><div><span>Our responsibility in one sentence</span><p>Give the client a secure, isolated and tested connection to the Adaptive Engine, then support them until their complete loop works safely.</p></div></section>
    <nav className="runbook-filters" aria-label="Filter runbook phases">{groups.map(x=><button className={group===x?"active":""} key={x} onClick={()=>setGroup(x)}>{x}</button>)}</nav>
    <section className="runbook-phases">{shown.map(phase=><details key={phase.number} open={phase.number<=3}><summary><button className={completed.includes(phase.number)?"complete":""} onClick={e=>{e.preventDefault();e.stopPropagation();toggle(phase.number)}} aria-label={`Mark phase ${phase.number} complete`}>{completed.includes(phase.number)?"✓":phase.number}</button><span><small>{phase.group} · Phase {phase.number}</small><strong>{phase.title}</strong></span><p>{phase.summary}</p><b>⌄</b></summary><div className="runbook-phase-body"><ul>{phase.checks.map(x=><li key={x}>✓ {x}</li>)}</ul>{phase.caution&&<aside><strong>Operator caution</strong>{phase.caution}</aside>}</div></details>)}</section>

    <div className="guidance-label"><span>CLI</span><div><h2>Environment and tenant commands</h2><p>Verify the environment before provisioning, and separate test from production.</p></div></div>
    <section className="content-grid equal"><article className="surface"><div className="surface-heading"><div><span>Environment gate</span><h3>Quality and integration checks</h3></div></div><CopyCode>{`npm run build\nnpm run lint\nnpm test\nTEST_DATABASE_URL=postgres://... npm run test:integration`}</CopyCode></article><article className="surface"><div className="surface-heading"><div><span>Tenant provisioning</span><h3>Test first, production after acceptance</h3></div></div><CopyCode>{`npm run tenant:create -- \\\n  --slug client-name-test \\\n  --name "Client Name — Test" \\\n  --environment test`}</CopyCode></article></section>

    <div className="guidance-label"><span>KEY</span><div><h2>Least-privilege scope guide</h2><p>For stronger production isolation, use separate keys for catalogue, runtime delivery and analytics.</p></div></div>
    <section className="scope-grid">{[["items:write","Synchronize item metadata and curriculum mappings"],["events:write","Report graded learner attempts"],["recommendations:read","Request next items and read curricula"],["mastery:read","Read learner progress and permitted analytics"]].map(([scope,why])=><article key={scope}><code>{scope}</code><p>{why}</p></article>)}</section>
    <section className="surface safe-default"><div><span>Safe tenant default</span><h3>Conservative until specifically approved</h3><p>Residency must be enforced by deployment architecture. Automatic retention enforcement is not implemented. Research participation remains disabled without reviewed authority and agreements.</p></div><CopyCode>{`{\n  "strategy": "balanced",\n  "researchParticipation": false,\n  "retentionDays": null\n}`}</CopyCode></section>

    <div className="guidance-label"><span>GO</span><div><h2>Production launch gate</h2><p>Every item needs a named owner and supporting evidence.</p></div></div>
    <section className="onboarding-checklist runbook-launch">{["Production tenant exists","Credentials delivered securely","Test keys absent from production","Catalogue synchronized and validated","Health, latency and error monitoring active","Alerts have named responders","Backups and restoration verified","Client fallback enabled","Pilot learner IDs are opaque","Research setting matches signed decision","Privacy and operational documents complete","Rollback triggers and owner documented","Support escalation hours agreed"].map(x=><label key={x}><input type="checkbox"/><i/><span>{x}</span></label>)}</section>
    <section className="narrative-strip"><span>Internal definition of done</span><blockquote>Test and production are separate; keys are least-privilege and server-only; metadata, learner loop, retries, failure handling, isolation, residency, privacy, monitoring, support and rollback all pass—and both parties accept the pilot checklist.</blockquote></section>
  </>;
}
