"use client";

import { useMemo, useState } from "react";

type PitchId="15"|"30"|"60"|"120";
const pitches:Record<PitchId,{label:string;time:string;audience:string;paragraphs:string[]}>= {
  "15":{label:"15-second pitch",time:"15 sec",audience:"A quick introduction",paragraphs:["Most learning applications still give every student roughly the same sequence, while building a safe adaptive system internally is expensive and difficult.","Adaptive Engine gives Canadian EdTech products a privacy-conscious API that recommends what each learner should practise next while the client keeps its content and identities."]},
  "30":{label:"30-second pitch",time:"30 sec",audience:"General conversation",paragraphs:["Learners do not arrive with the same knowledge, but most educational software still follows fixed sequences. Companies that want personalization must either build complex learner modelling themselves or send sensitive content and data to a large platform.","Adaptive Engine offers a third option: a Canadian, API-first adaptive-learning service. Clients keep their question content, answer keys, user accounts, and learner interface.","We receive pseudonymous learning events and return explainable, curriculum-aware recommendations—giving Canadian EdTech companies and publishers a faster path to adaptive practice without rebuilding their entire product."]},
  "60":{label:"60-second founder pitch",time:"1 min",audience:"Partner or programme meeting",paragraphs:["Every learner has different strengths, gaps, and rates of forgetting, yet much educational software still delivers one fixed path. Creating a trustworthy adaptive system requires learner modelling, curriculum structure, item analytics, privacy engineering, experimentation, and years of learning data.","Adaptive Engine is building that capability as Canadian educational infrastructure. A company connects its existing app and question bank through an API. It keeps the question text, answer keys, learner identities, and grading. We receive only pseudonymous IDs, item metadata, and graded outcomes.","The engine builds a learner profile and returns the next recommended item with a reason, confidence measure, target curriculum concept, and algorithm version.","We are starting with Ontario-aligned practice and an architecture for province-specific curricula, English and French metadata, Canadian hosting, tenant isolation, and explainability.","We are seeking a qualified design partner to validate the engine in real learning workflows and prove measurable educational and commercial value."]},
  "120":{label:"Two-minute investor pitch",time:"2 min",audience:"Investor or strategic buyer",paragraphs:["Education is inherently personal, but most digital learning products still deliver content in a predetermined order. Implementing adaptation well requires specialized learning science, data infrastructure, curriculum modelling, experimentation, privacy controls, and enough events to validate the models.","This creates a build-versus-buy problem. Building internally is slow and difficult to validate. Buying a full platform can mean surrendering content ownership, user experience, or sensitive data.","Adaptive Engine is a content-agnostic API with a different boundary. The client keeps content, answer keys, grading, and learner identity. We receive a pseudonymous learner ID, item metadata, and each attempt outcome. We return an explainable recommendation and maintain a versioned learner model.","Canada is a strong starting point because education is governed by provinces and territories. Buyers navigate jurisdiction-specific curricula, English and French requirements, accessibility, children’s privacy, procurement, and Canadian data expectations.","Our foundation includes a multi-tenant API, scoped credentials, pseudonymous profiles, adaptive session goals, idempotent events, explainable decisions, content analytics, cohort suppression, and research participation disabled by default.","The next step is not to claim the science is proven. It is to integrate with qualified design partners, evaluate real workflows, calibrate models, and build credible evidence.","Our business model hypothesis is an annual B2B platform agreement, with implementation and curriculum services where appropriate. Defensibility comes from validated models, trusted Canadian operations, deep integrations, and accumulated evidence.","We are seeking a design partner and research support to process authorized learning events, demonstrate predefined educational and commercial outcomes, and complete the evidence required for Canadian institutional adoption."]}
};
const story=[
  {letter:"P",word:"Problem",cue:"Fixed paths ignore different strengths, gaps, and rates of forgetting.",question:"What painful problem exists now?"},
  {letter:"B",word:"Buyer",cue:"Canadian EdTech companies and publishers need adaptation without building a research team.",question:"Who owns the pain and budget?"},
  {letter:"P",word:"Product",cue:"An API recommends the next activity; the client keeps content, identity, grading, and UI.",question:"What exactly do we provide?"},
  {letter:"W",word:"Why Canada",cue:"Province-specific curricula, bilingual readiness, residency, privacy, accessibility, and procurement.",question:"Why begin here?"},
  {letter:"D",word:"Difference",cue:"Content-agnostic, pseudonymous, explainable, province-aware infrastructure—not another learning app.",question:"Why this instead of an alternative?"},
  {letter:"E",word:"Evidence",cue:"Foundation exists; real-workflow validation and outcome evidence come next.",question:"What can we prove today?"},
  {letter:"A",word:"Ask",cue:"A qualified design partner, research support, technical collaborator, or investment tied to milestones.",question:"What should this person do next?"},
];
const problems=["Different learners need different paths","Fixed sequences become too easy or too hard","Teachers cannot personalize every interaction at scale","Content owners lack item-effectiveness evidence","Internal adaptive systems require specialized research and engineering","Canadian adoption adds curriculum, language, accessibility, privacy and procurement","Organizations want to keep their content and learner experience"];

export function PitchToolkit(){
 const [pitch,setPitch]=useState<PitchId>("30");const [line,setLine]=useState(0);const [recall,setRecall]=useState<number|null>(null);const [ask,setAsk]=useState("a qualified design partner");const active=useMemo(()=>({...pitches[pitch],paragraphs:pitches[pitch].paragraphs.map(p=>p.replace("a qualified design partner",ask))}),[pitch,ask]);
 const choose=(id:PitchId)=>{setPitch(id);setLine(0)}; const speak=()=>{if("speechSynthesis" in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(active.paragraphs.join(" ")))}};
 return <>
  <header className="section-header"><div className="eyebrow"><span/>Founder rehearsal studio</div><h1>Master the Adaptive Engine story.</h1><p>Choose the audience, learn one memorable structure, rehearse in short sections, and test recall until the story sounds natural rather than memorized.</p></header>
  <section className="pitch-one-line"><span>The company in one sentence</span><blockquote>Adaptive Engine is privacy-conscious Canadian learning infrastructure that helps education applications and publishers choose the right activity for each learner—without surrendering content, answer keys, or student identities.</blockquote><button onClick={()=>navigator.clipboard.writeText("Adaptive Engine is privacy-conscious Canadian learning infrastructure that helps education applications and publishers choose the right activity for each learner—without surrendering content, answer keys, or student identities.")}>Copy</button></section>

  <div className="guidance-label"><span>7</span><div><h2>Remember one spine: PBPWDEA</h2><p>Every version follows the same seven beats. Length changes; the story does not.</p></div></div>
  <section className="pitch-spine">{story.map((s,i)=><article key={`${s.letter}${s.word}`}><i>{s.letter}</i><span>{String(i+1).padStart(2,"0")}</span><h3>{s.word}</h3><p>{s.cue}</p></article>)}</section>
  <div className="memory-phrase"><strong>Memory phrase</strong><span>Problem Buyers Prefer What Differentiated Evidence Asks.</span><small>Use the letters as prompts, not as words you say aloud.</small></div>

  <section className="pitch-selector"><div>{(Object.keys(pitches) as PitchId[]).map(id=><button className={pitch===id?"active":""} key={id} onClick={()=>choose(id)}><strong>{pitches[id].time}</strong><span>{pitches[id].audience}</span></button>)}</div><label>Your ask<select value={ask} onChange={e=>setAsk(e.target.value)}><option>a qualified design partner</option><option>research funding</option><option>a technical collaborator</option><option>strategic investment</option></select></label></section>
  <section className="rehearsal-card"><header><div><span>Selected script</span><h2>{active.label}</h2><p>{active.audience} · target {active.time}</p></div><button onClick={speak}>▶ Read aloud</button></header><div className="rehearsal-progress">{active.paragraphs.map((_,i)=><i className={i<=line?"active":""} key={i}/>)}</div><article><span>Beat {line+1} of {active.paragraphs.length}</span><p>{active.paragraphs[line]}</p></article><footer><button disabled={line===0} onClick={()=>setLine(n=>n-1)}>← Previous</button><small>Read it aloud twice, then say it once without looking.</small><button disabled={line===active.paragraphs.length-1} onClick={()=>setLine(n=>n+1)}>Next beat →</button></footer></section>

  <section className="pitch-full"><header><div><span>Full script</span><h2>Read for rhythm</h2></div><button onClick={()=>navigator.clipboard.writeText(active.paragraphs.join("\n\n"))}>Copy script</button></header>{active.paragraphs.map((p,i)=><p key={i}><i>{i+1}</i>{p}</p>)}</section>

  <div className="guidance-label"><span>?</span><div><h2>Recall drill</h2><p>Answer the question before revealing the cue. Retrieval practice builds memory faster than rereading.</p></div></div>
  <section className="recall-grid">{story.map((s,i)=><button className={recall===i?"revealed":""} key={s.word} onClick={()=>setRecall(recall===i?null:i)}><span>{s.letter} · {s.word}</span><strong>{recall===i?s.cue:s.question}</strong><small>{recall===i?"Tap to hide":"Think, then reveal"}</small></button>)}</section>

  <section className="pitch-analogy"><div><span>Simple analogy</span><h2>The decision-making layer behind a learning application.</h2><p>The client owns the classroom experience and content. The engine learns from pseudonymous outcomes and recommends what the learner should practise next.</p></div><div><b>Client app</b><span>owns content, identity, grading, and UI</span><i>↔</i><b>Adaptive Engine</b><span>owns the next-practice decision</span></div></section>

  <div className="guidance-label"><span>!</span><div><h2>Problem components</h2><p>Use only the three most relevant to your audience.</p></div></div>
  <section className="problem-chips">{problems.map((p,i)=><article key={p}><i>{i+1}</i><span>{p}</span></article>)}</section>
  <section className="pitch-guardrails"><article><span>Say confidently</span><ul><li>The API and privacy boundary exist</li><li>The client keeps content, identities and grading</li><li>The architecture supports explainable decisions</li><li>Real-world validation is the next milestone</li></ul></article><article><span>Do not overclaim</span><ul><li>Do not say learning outcomes are already proven</li><li>Do not call a hypothesis a customer fact</li><li>Do not invent market, partner or event numbers</li><li>Remove every unsupported claim or placeholder</li></ul></article></section>
  <section className="practice-routine"><header><span>A five-minute daily routine</span><h2>Read less. Recall more.</h2></header>{[["1 min","Say PBPWDEA from memory"],["1 min","Deliver the 15-second pitch twice"],["1 min","Answer three recall cards"],["1 min","Deliver the current audience pitch"],["1 min","Name one weak line and simplify it"]].map(([t,x],i)=><div key={x}><i>{i+1}</i><strong>{t}</strong><span>{x}</span></div>)}</section>
 </>;
}
